import {useEffect,useState} from 'react'

const icons={leaf:'M4 20C-1 10 9 4 21 3c0 13-5 20-14 16M3 23 16 9',heart:'M12 21 3 12C-3 4 7-2 12 5c5-7 15-1 9 7Z',users:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm8-1a3 3 0 0 0 0-6m1 11a4 4 0 0 1 4 4v2',shield:'M12 2c3 3 6 4 9 4v7c0 5-5 8-9 10-4-2-9-5-9-10V6c3 0 6-1 9-4Zm-5 10 4 4 6-7',truck:'M2 6h13v12H2zM15 11h4l4 5v2h-8M5 18a2 2 0 1 0 0 4 2 2 0 0 0 0-4Zm14 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4',drop:'M12 2S5 10 5 15a7 7 0 0 0 14 0c0-5-7-13-7-13Z',gear:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8Zm0-5 1 3 3 1 3-1 1 3-2 2v3l2 2-1 3-3-1-3 1-3-1-3 1-1-3 2-2v-3L4 9l1-3 3 1 3-1 1-3Z',box:'m3 6 9-4 9 4v12l-9 4-9-4V6Zm0 0 9 5 9-5M12 11v11',star:'m12 2 3 6 6 .8-4.5 4.5 1 6.7-5.5-3-5.5 3 1-6.7L3 8.8 9 8Z'}
function Icon({name}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={icons[name]}/></svg>}
const reasons=[['leaf','100% Natural','No artificial additives, just pure goodness.'],['heart','Rich in Nutrition','A healthy snack packed with protein & fiber.'],['shield','Hygienically Processed','Clean, safe and quality checked at every step.'],['users','Support Local Farmers','Empowering farming communities in Bihar.']]
const process=[['leaf','Sourcing','Handpicked from Bihar’s finest farms'],['drop','Cleaning','Carefully cleaned and sorted'],['gear','Processing','Hygienically processed'],['shield','Quality Check','Strict quality assurance'],['box','Packaging','Packed with care'],['truck','Delivered to You','Fresh at your doorstep']]
function Heading({title,sub}){return <header className="about-heading"><Icon name="leaf"/><h2>{title}</h2><small>{sub}</small></header>}

export default function AboutPage(){
 const [impactOpen,setImpactOpen]=useState(false)
 useEffect(()=>{if(!impactOpen)return;const close=e=>{if(e.key==='Escape')setImpactOpen(false)};document.body.style.overflow='hidden';window.addEventListener('keydown',close);return()=>{document.body.style.overflow='';window.removeEventListener('keydown',close)}},[impactOpen])
 return <main className="about-page">
 <section className="about-hero about-art-banner"><img src="/about-hero-banner.png" alt="Our story, our purpose. Good Food, Brighter Tomorrow. Premium natural makhana from Meena Green."/></section>
 <section className="story-section" id="our-story"><Heading title="About Meena Green" sub="TRADITION MEETS A HEALTHIER TOMORROW"/><div className="story-grid"><div className="story-image"><img src="/farmer-from-our-farms.png" alt="Bihar farmer harvesting makhana"/><b>From Bihar<br/>With Love</b></div><div className="story-copy"><h3>Bringing <em>Nature’s Superfood</em><br/>to Every Home</h3><p>Meena Green was founded with a simple belief — healthy snacking should be natural, pure and accessible to everyone. Sourced from the fertile lands of Bihar, our makhana is carefully processed, hygienically packed, and delivered with love to your home.</p><p>We work closely with local farmers to ensure fair practices, premium quality and sustainable growth for our communities.</p><a href="/products">Our Products <span>→</span></a></div></div></section>
 <section className="about-stats">{[['users','10,000+','Happy Customers'],['truck','50+','Tons Delivered'],['leaf','500+','Farmers Supported'],['star','4.8/5','Customer Rating']].map(([i,n,t])=><div key={t}><Icon name={i}/><b>{n}</b><span>{t}</span></div>)}</section>
 <section className="why-section"><Heading title="Why Choose Meena Green?" sub="GOODNESS YOU CAN TRUST"/><div className="reason-grid">{reasons.map(([i,t,p])=><article key={t}><span><Icon name={i}/></span><h3>{t}</h3><p>{p}</p></article>)}</div></section>
 <section className="process-section"><Heading title="Our Process" sub="FROM FARM TO YOUR HOME"/><div className="process-row">{process.map(([i,t,p],index)=><article key={t}><span><Icon name={i}/></span><h3>{t}</h3><p>{p}</p>{index<process.length-1&&<i>→</i>}</article>)}</div></section>
 <section className="farmer-impact"><div><h2>Empowering<br/>Farmers, Building<br/><em>a Healthier India</em></h2><p>We are committed to supporting local farmers and promoting sustainable farming practices. By choosing Meena Green, you are not just choosing a healthy snack, but also contributing to a better livelihood for farming communities.</p><button type="button" onClick={()=>setImpactOpen(true)}>Our Impact <span>→</span></button></div><img src="/farmer-from-our-farms.png" alt="Farmer holding freshly harvested makhana"/></section>
 <section className="values-section" id="values"><Heading title="Our Values" sub="THE PRINCIPLES THAT GUIDE US"/><div className="reason-grid">{[['shield','Quality First','We never compromise on quality.'],['heart','Health & Wellness','Your health is our priority.'],['users','Community Growth','Together with farmers for a better future.'],['leaf','Sustainability','Caring for nature today for tomorrow.']].map(([i,t,p])=><article key={t}><span><Icon name={i}/></span><h3>{t}</h3><p>{p}</p></article>)}</div></section>
 <section className="about-cta"><img src="/sandesh-cutout.png" alt="Premium makhana"/><h2>Let’s Snack<br/>A Healthier Tomorrow</h2><p>Join thousands of happy customers<br/>who trust Meena Green.</p><a href="/products">Shop Now <span>→</span></a></section>
 {impactOpen&&<div className="impact-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setImpactOpen(false)}}><section className="impact-modal" role="dialog" aria-modal="true" aria-labelledby="impact-title"><button className="impact-close" onClick={()=>setImpactOpen(false)} aria-label="Close impact popup">×</button><div className="impact-content"><div className="impact-farmer"><img src="/about-farmer-impact.png" alt="Local farmer holding freshly harvested makhana"/></div><div className="impact-details"><header><Icon name="leaf"/><small>OUR IMPACT</small><h2 id="impact-title">Small Bites, <em>A Bigger Impact</em></h2><p>At Meena Green, we believe good food can do more. Every pack of makhana you choose supports farmers, healthy living, and a more sustainable future.</p></header><div className="impact-cards">{[['users','Supporting Local Farmers','We work directly with farmers to ensure fair prices and long-term partnerships.'],['leaf','Sustainable Farming Practices','We encourage eco-friendly and responsible farming methods to protect our environment.'],['heart','Healthier Communities','We provide natural, nutritious snacks that support healthier lifestyles for families.'],['shield','A Greener Tomorrow','By choosing Meena Green, you contribute to a cleaner planet and a more sustainable food system.']].map(([i,t,p])=><article key={t}><span><Icon name={i}/></span><h3>{t}</h3><p>{p}</p></article>)}</div><div className="impact-benefits">{[['leaf','Pure & Natural','No artificial additives'],['heart','Better Nutrition','Goodness in every bite'],['users','Stronger Rural Communities','Empowering livelihoods'],['shield','Sustainable Future','For generations to come']].map(([i,t,p])=><div key={t}><Icon name={i}/><span><b>{t}</b><small>{p}</small></span></div>)}</div><div className="impact-quote"><blockquote>“When you choose Meena Green, you’re not just enjoying a snack — you’re supporting farmers, families and a healthier planet.”</blockquote><div className="impact-bowl" aria-hidden="true">✦</div></div><footer className="impact-footer"><div><span><Icon name="leaf"/></span>Sourced Directly<br/>from Bihar</div><div><span><Icon name="leaf"/></span>Tradition Meets<br/>Modern Quality</div><div><span><Icon name="shield"/></span>Trusted by<br/>Health-Conscious Families</div><a href="/products" onClick={()=>setImpactOpen(false)}>Explore Our Products <span>→</span></a></footer></div></div></section></div>}
 </main>}
