import {useState} from 'react'
import StoreNavbar from './StoreNavbar'
import AccountSidebar from './AccountSidebar'

const paths={bag:<><path d="M5 8h14l-1 13H6L5 8Z"/><path d="M9 9V6a3 3 0 0 1 6 0v3"/></>,pin:<><path d="M19 10c0 5-7 12-7 12S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/></>,heart:<path d="M20.8 5.6a5.2 5.2 0 0 0-7.4 0L12 7l-1.4-1.4a5.2 5.2 0 0 0-7.4 7.4L12 21l8.8-8a5.2 5.2 0 0 0 0-7.4Z"/>,user:<><circle cx="12" cy="7" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>,headset:<><path d="M4 14v-2a8 8 0 0 1 16 0v2M4 14h3v6H5a1 1 0 0 1-1-1v-5Zm16 0h-3v6h2a1 1 0 0 0 1-1v-5Z"/></>,logout:<><path d="M10 17l5-5-5-5M15 12H3M14 4h5a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2h-5"/></>,edit:<><path d="m4 20 4.5-1 10-10a2.1 2.1 0 0 0-3-3l-10 10L4 20ZM14 7l3 3"/></>,mail:<><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m4 7 8 6 8-6"/></>,phone:<path d="M6.5 3h3l1.5 5-2 1.5a16 16 0 0 0 5.5 5.5l1.5-2 5 1.5v3c0 2-1.6 3.6-3.6 3.5C9.8 20.4 3.6 14.2 3.1 6.6 3 4.6 4.5 3 6.5 3Z"/>,cart:<><path d="M3 4h2l2 10h11l2-7H6M9 20h.01M17 20h.01"/></>,trash:<><path d="M4 7h16M9 7V4h6v3m3 0-1 14H7L6 7m4 4v6m4-6v6"/></>}
function Icon({name,className='h-5 w-5'}){return <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" aria-hidden="true">{paths[name]}</svg>}
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
export default function AccountWishlistPage({products}){
 const profile=read('meena-profile',{name:'Meena Customer',email:'customer@meenagreen.in',phone:'+91 98765 43210'})
 const [liked,setLiked]=useState(()=>read('meena-wishlist',[])),[cart,setCart]=useState(()=>read('meena-cart',{}))
 const items=products.filter(product=>liked.includes(product.name)),initials=(profile.name||'Meena Customer').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()
 const saveLiked=next=>{setLiked(next);localStorage.setItem('meena-wishlist',JSON.stringify(next))}
 const add=name=>{const next={...cart,[name]:(cart[name]||0)+1};setCart(next);localStorage.setItem('meena-cart',JSON.stringify(next))}
 const cartCount=Object.values(cart).reduce((sum,value)=>sum+value,0)
 return <><StoreNavbar wishlistCount={liked.length} cartCount={cartCount}/><main className="min-h-screen bg-[#fffaf0] px-4 py-10 text-[#103d30] lg:px-8"><div className="mx-auto grid max-w-[1480px] items-start gap-6 lg:grid-cols-[270px_1fr]">
  <AccountSidebar active="Wishlist" wishlistCount={liked.length}/>
  <section className="space-y-5"><div className="flex min-h-[138px] flex-wrap items-center gap-6 rounded-[22px] border border-[#e1e6dd] bg-white px-10 py-6 shadow-sm"><span className="grid h-20 w-20 place-items-center rounded-full border-4 border-white bg-[#087047] text-3xl font-bold text-white shadow-lg">{initials}</span><div className="min-w-0 flex-1"><h1 className="font-serif text-4xl font-bold text-[#075e3a]">{profile.name}</h1><div className="mt-2 flex flex-wrap gap-5 text-slate-500"><span className="flex items-center gap-2"><Icon name="mail"/>{profile.email||'Email not added'}</span><span className="flex items-center gap-2"><Icon name="phone"/>{profile.phone||'Phone not added'}</span></div></div><a href="/profile" className="inline-flex h-12 items-center gap-2 rounded-xl border border-[#b9d1c2] px-6 font-semibold text-[#08623f]"><Icon name="edit"/>Edit Profile</a></div>
   <div className="rounded-[22px] border border-[#e1e6dd] bg-white p-6 shadow-sm"><header className="mb-6 flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-4"><span className="grid h-14 w-14 place-items-center rounded-full bg-[#dcf8df] text-[#087345]"><Icon name="heart" className="h-8 w-8"/></span><div><h2 className="font-serif text-4xl font-bold text-[#075e3a]">My Wishlist</h2><p className="text-lg text-slate-500">Your saved favourites, ready whenever you are.</p></div></div><div className="flex items-center gap-5"><span className="text-lg">{items.length} Items</span><button onClick={()=>saveLiked([])} className="inline-flex h-12 items-center gap-2 rounded-xl !border !border-red-200 !bg-red-50 px-5 !font-semibold !text-red-600"><Icon name="trash"/>Clear Wishlist</button></div></header>
    <div className="space-y-3">{items.map(product=><article key={product.name} className="grid items-center gap-5 rounded-2xl border border-[#dce5df] p-5 sm:grid-cols-[135px_1fr_100px_235px_28px]"><img src={product.image} alt={product.name} className="mx-auto h-32 w-28 object-contain"/><div><h3 className="text-xl font-bold">{product.name}</h3><p className="mt-2 text-slate-500">250g Pack</p><p className="font-semibold text-[#087345]">₹{product.price}</p><span className="mt-2 inline-block rounded-lg bg-[#e4f6e5] px-3 py-1 text-sm text-[#267544]">In Stock</span></div><strong className="text-2xl text-[#087345]">₹{product.price}</strong><div className="grid gap-2"><button onClick={()=>add(product.name)} className="inline-flex h-12 items-center justify-center gap-3 rounded-xl !border-0 !bg-[#ff5a0a] !text-base !font-semibold !text-white hover:!bg-[#ec4e00]"><Icon name="cart"/>Add to Cart</button><a href="/products" className="inline-flex h-11 items-center justify-center rounded-lg border border-[#cbd8d1] font-semibold text-[#123d35]">View Product</a></div><button onClick={()=>saveLiked(liked.filter(name=>name!==product.name))} className="self-start !border-0 !bg-transparent !text-3xl !font-light !text-[#22585a]" aria-label={`Remove ${product.name}`}>×</button></article>)}{!items.length&&<div className="rounded-2xl border border-dashed border-[#a9cbb8] p-14 text-center"><Icon name="heart" className="mx-auto h-12 w-12 text-[#8bb99d]"/><h3 className="mt-4 text-xl font-bold">Your wishlist is empty</h3><a href="/products" className="mt-5 inline-flex rounded-xl bg-[#087345] px-6 py-3 font-semibold text-white">Explore Products</a></div>}</div>
   </div>
  </section></div></main></>
}
