import { useEffect, useMemo, useState } from 'react'
import './App.css'

const products = [
  { name:'Meena Premium', type:'Plain Makhana', price:180, image:'/premium-yellow-new.png' },
  { name:'Perfect Premium', type:'Plain Makhana', price:190, image:'/perfect-yellow-new.png' },
  { name:'Perfect-2', type:'Premium Makhana', price:190, image:'/perfect-purple-new.png' },
  { name:'Sandesh Organic', type:'Organic Makhana', price:170, image:'/sandesh-new.jpeg' },
]
const filters=['All Products','Plain Makhana','Roasted Makhana','Flavoured Makhana','Gift Packs']
const banners=[
 {src:'/banner-nature.png',alt:'Meena Green makhana — from nature’s fields to your home'},
 {src:'/banner-offer.png',alt:'Special offer — up to 20% off on makhana products'},
 {src:'/banner-superfood.png',alt:'Premium Makhana — nature’s superfood'},
]

function App(){
 const [filter,setFilter]=useState('All Products'),[cart,setCart]=useState(0),[liked,setLiked]=useState([]),[menu,setMenu]=useState(false),[slide,setSlide]=useState(0),[paused,setPaused]=useState(false)
 const shown=useMemo(()=>filter==='All Products'||filter==='Plain Makhana'?products:products.filter(p=>p.type===filter),[filter])
 const toggle=(name)=>setLiked(x=>x.includes(name)?x.filter(v=>v!==name):[...x,name])
 useEffect(()=>{if(paused)return;const timer=setInterval(()=>setSlide(s=>(s+1)%banners.length),5000);return()=>clearInterval(timer)},[paused])
 const moveSlide=(direction)=>setSlide(s=>(s+direction+banners.length)%banners.length)
 return <>
  <div className="promise-bar"><span>🌿 100% Natural　|　⊘ No Preservatives　|　⚡ Rich in Nutrition　|　🤝 Trusted by Families</span><b>🚚 Free Shipping on Orders Above ₹499</b></div>
  <div className="nav-wrap"><header className="site-header"><a className="logo" href="#home"><img src="/meena-logo-premium.png" alt="Meena Green"/></a><div className="delivery"><span>●</span><p>Deliver to<strong>Purnea, Bihar　⌄</strong></p></div><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Toggle menu">☰</button><nav className={menu?'open':''}><a className="active" href="#home"><span>⌂</span> Home</a><a href="#products">Products　⌄</a><a href="#about">About Us</a><a href="#contact">Contact</a></nav><div className="actions"><button aria-label="Search">⌕</button><button aria-label="Account">♙</button><button aria-label={'Cart '+cart}>🛒<i>{cart}</i></button></div></header></div>
  <main>
   <section className="banner-carousel" id="home" aria-label="Featured offers" onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)} onFocus={()=>setPaused(true)} onBlur={()=>setPaused(false)}><div className="banner-track" style={{transform:`translateX(-${slide*100}%)`}}>{banners.map((banner,index)=><img key={banner.src} src={banner.src} alt={banner.alt} aria-hidden={slide!==index}/>)}</div><button className="banner-arrow prev" onClick={()=>moveSlide(-1)} aria-label="Previous banner">‹</button><button className="banner-arrow next" onClick={()=>moveSlide(1)} aria-label="Next banner">›</button><div className="banner-dots">{banners.map((_,index)=><button key={index} className={slide===index?'active':''} onClick={()=>setSlide(index)} aria-label={`Show banner ${index+1}`} aria-current={slide===index?'true':undefined}/>)}</div></section>
   <section className="quality-strip"><div>🌿 <span><b>Premium Quality</b><small>Carefully selected</small></span></div><div>🌱 <span><b>Hygienically Packed</b><small>Freshness sealed</small></span></div><div>♨ <span><b>Farm Fresh Goodness</b><small>From Bihar farms</small></span></div><div>♡ <span><b>A Healthier You Always</b><small>Wholesome everyday</small></span></div></section>
   <section className="products section" id="products"><div className="section-heading"><span>🌿</span><div><h2>Our Products</h2><p>Explore our range of premium makhana, carefully sourced and packed with purity.</p></div><span>🌿</span></div><div className="filters">{filters.map(f=><button className={filter===f?'selected':''} onClick={()=>setFilter(f)} key={f}>{f}</button>)}</div><div className="cards">{shown.length?shown.map(p=><article key={p.name}><button className={'heart '+(liked.includes(p.name)?'liked':'')} onClick={()=>toggle(p.name)} aria-label={'Favourite '+p.name}>♥</button><img src={p.image} alt={p.name}/><h3>{p.name}</h3><p>{p.type}</p><small>250g</small><strong>₹{p.price}</strong><button className="add" onClick={()=>setCart(c=>c+1)}>🛒　Add to Cart</button></article>):<p className="empty">Coming soon — our newest flavours are being prepared.</p>}</div></section>
   <section className="nature"><div><h2>Choose Your Way<br/>to Healthy Living</h2><p>Available in Retail and Wholesale<br/>for every need.</p><a href="#modes">Explore Now　→</a></div><div className="nature-bowl"><span>Nature's<br/><i>Superfood</i></span><div>● ● ● ●<br/> ● ● ● ● ●<br/>● ● ● ●</div></div><ul><li>♙ Low in Calories</li><li>♧ High in Protein</li><li>✺ Rich in Antioxidants</li><li>⌁ Gluten Free</li></ul></section>
   <section className="modes" id="modes"><article className="retail"><div><span>⌂</span><h2>Retail Mode</h2><p>For Individual Customers</p><ul><li>Small Packs, Big Goodness</li><li>Best for Home Use</li><li>Wide Range of Products</li><li>Healthy Snacks for Your Family</li></ul><button>Shop Retail　→</button></div><img src="/premium-yellow-new.png" alt="Retail makhana"/></article><article className="wholesale"><div><span>◇</span><h2>Wholesale Mode</h2><p>For Businesses & Resellers</p><ul><li>Bulk Packaging</li><li>Best Wholesale Prices</li><li>Consistent Quality</li><li>Grow Your Business with Us</li></ul><button>Enquire Now　→</button></div><div className="boxes"><b>MEENA<br/>GREEN</b><b>MEENA<br/>GREEN</b><b>MEENA<br/>GREEN</b></div></article></section>
   <section className="about" id="about"><div><h2>🌿 About MEENA Green.</h2><h3>Pure Snacks. Healthier Lives.</h3><p>MEENA Green is committed to bringing you the finest quality makhana, sourced from trusted farms and packed with care. Our mission is to promote healthy snacking with 100% natural, nutritious and great tasting products.</p><a href="#contact">Know More　→</a></div><div className="about-visual"><span>From<br/><i>Nature</i><br/>To You</span><img src="/sandesh-new.jpeg" alt="Natural makhana from Bihar"/></div></section>
   <section className="final-strip"><span>🌿 <b>100% Natural</b><small>No artificial colors & flavours</small></span><span>♧ <b>Hygienically Processed</b><small>Clean & safe production</small></span><span>♢ <b>No Added Preservatives</b><small>Pure and healthy</small></span><span>🚚 <b>Pan India Delivery</b><small>Fast & reliable shipping</small></span></section>
  </main>
  <footer id="contact"><div className="footer-grid"><div className="footer-brand"><img src="/logo-new.png" alt="Meena Green"/><h3>Healthy Snacking<br/>Happier You</h3><p>Premium quality makhana for a healthier and happier life.</p><b>◉　◎　▣　◉</b></div><div><h3>Quick Links</h3><a href="#home">Home</a><a href="#products">Products</a><a href="#about">About Us</a><a href="#modes">Retail Mode</a><a href="#contact">Contact Us</a></div><div><h3>Our Products</h3><a href="#products">Plain Makhana</a><a href="#products">Roasted Makhana</a><a href="#products">Flavoured Makhana</a><a href="#products">Gift Packs</a></div><div><h3>Customer Care</h3><a href="#contact">Help Center</a><a href="#contact">Shipping Policy</a><a href="#contact">Return Policy</a><a href="#contact">Order Tracking</a></div><div><h3>Contact Us</h3><p>☎　+91 98765 43210</p><p>✉　care@meenagreen.in</p><p>⌖　Purnea, Bihar, India</p><p>◷　Mon–Sat: 9AM–7PM</p></div></div><div className="subscribe"><span>✉　<b>Stay Updated</b><small>Get latest offers, new products and health tips.</small></span><form onSubmit={e=>e.preventDefault()}><input type="email" placeholder="Enter your email address" aria-label="Email address"/><button>Subscribe</button></form><b>We Accept　▣ VISA　▣ UPI</b></div><div className="copyright">© 2026 MEENA Green. All Rights Reserved.<span>Healthy Today, Brighter Tomorrow 🌿</span></div></footer>
 </>
}
export default App
