import {useMemo,useState} from 'react'
import StoreNavbar from './StoreNavbar'
import Footer from './Footer'

const extraProducts=[
 {name:'Meena Classic',type:'Plain Makhana',price:155,image:'/makhana-classic-red.jpg'},
 {name:'Premium Select',type:'Premium Makhana',price:210,image:'/makhana-premium-yellow.png'},
 {name:'Perfect Gold',type:'Premium Makhana',price:195,image:'/makhana-perfect-yellow.png'},
 {name:'Perfect Purple',type:'Roasted Makhana',price:205,image:'/makhana-perfect-purple.png'},
]
function saved(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function Icon({name,className='h-6 w-6'}){const paths={cart:'M3 4h2l2 10a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2l2-7H6m4 13h.01M17 20h.01',trash:'M4 7h16M9 7V4h6v3m-9 0 1 14h10l1-14M10 11v6m4-6v6',heart:'M20.8 5.5a5.1 5.1 0 0 0-7.2 0L12 7.1l-1.6-1.6a5.1 5.1 0 1 0-7.2 7.2L12 21l8.8-8.3a5.1 5.1 0 0 0 0-7.2Z',leaf:'M20 4C11 4 5 9 5 18c9 0 15-5 15-14ZM5 18 20 4M7 19c3 0 5 1 7 3',file:'M6 2h8l4 4v16H6zM14 2v5h5M9 12h6m-6 4h6',truck:'M3 7h11v10H3zm11 4h4l3 3v3h-7M7 20a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm10 0a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z',lock:'M6 10h12v11H6zM9 10V7a3 3 0 0 1 6 0v3',user:'M20 21a8 8 0 0 0-16 0m12-13a4 4 0 1 1-8 0 4 4 0 0 1 8 0Z',shield:'M12 3c3 3 6 4 9 4v6c0 5-4 8-9 10-5-2-9-5-9-10V7c3 0 6-1 9-4Z',box:'m12 3 9 5v9l-9 5-9-5V8l9-5Zm0 9 9-4M12 12 3 8m9 4v10',headset:'M4 14v-2a8 8 0 0 1 16 0v2M4 14h3v6H5a1 1 0 0 1-1-1zm16 0h-3v6h2a1 1 0 0 0 1-1z'};return <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]}/></svg>}

export default function CartPage({products}){
 const allProducts=useMemo(()=>[...products,...extraProducts],[products])
 const [cart,setCart]=useState(()=>saved('meena-cart',{}))
 const [liked,setLiked]=useState(()=>saved('meena-wishlist',[]))
 const [notice,setNotice]=useState('')
 const items=allProducts.filter(product=>cart[product.name]>0)
 const itemCount=Object.values(cart).reduce((sum,count)=>sum+count,0)
 const subtotal=items.reduce((sum,product)=>sum+product.price*cart[product.name],0)
 const tax=Math.round(subtotal*.05)
 const total=subtotal+tax
 const saveCart=next=>{setCart(next);localStorage.setItem('meena-cart',JSON.stringify(next))}
 const change=(name,delta)=>{const next={...cart,[name]:Math.max(0,(cart[name]||0)+delta)};if(!next[name])delete next[name];saveCart(next)}
 const remove=name=>{const next={...cart};delete next[name];saveCart(next);setNotice(`${name} removed from cart`)}
 const toggleWish=name=>{const next=liked.includes(name)?liked.filter(item=>item!==name):[...liked,name];setLiked(next);localStorage.setItem('meena-wishlist',JSON.stringify(next));setNotice(next.includes(name)?`${name} saved to wishlist`:`${name} removed from wishlist`)}
 return <div className="cart-page min-h-screen bg-[#fffdf8] text-[#092f24]">
  <StoreNavbar active="" wishlistCount={liked.length} cartCount={itemCount}/>
  <main className="mx-auto max-w-[1450px] px-[clamp(16px,4vw,62px)] py-6">
   <div className="mb-5 flex flex-wrap items-end justify-between gap-5"><div><p className="m-0 mb-6 text-sm text-[#5d7066]"><a href="/">Home</a><span className="mx-3">›</span><b>Cart</b></p><div className="flex items-center gap-4"><span className="grid h-14 w-14 place-items-center rounded-full bg-[#e7f5e3] text-[#087044]"><Icon name="cart" className="h-8 w-8"/></span><div><h1 className="m-0 font-serif text-[clamp(32px,3vw,46px)]">Your Cart ({itemCount} {itemCount===1?'Item':'Items'})</h1><p className="mb-0 mt-1 text-sm text-[#67766d]">Review your items and proceed to checkout</p></div></div></div><a className="mb-1 inline-flex min-h-12 items-center gap-3 rounded-lg border border-[#087044] px-6 font-semibold text-[#075c38] no-underline" href="/products">← &nbsp; Continue Shopping</a></div>

   {items.length?<div className="grid items-start gap-5 lg:grid-cols-[minmax(0,2.25fr)_minmax(300px,1fr)]"><section className="overflow-hidden rounded-xl border border-[#dce5dd] bg-white shadow-[0_7px_24px_#1739230c]">
    <div>{items.map(product=><article className="grid grid-cols-[90px_minmax(0,1fr)] gap-4 border-b border-[#e5eae5] p-4 last:border-0 sm:grid-cols-[120px_minmax(0,1fr)_auto] sm:items-center" key={product.name}><img className="h-28 w-full object-contain sm:h-32" src={product.image} alt={product.name}/><div className="min-w-0"><div className="flex flex-wrap items-center gap-3"><h2 className="m-0 text-lg font-semibold">{product.name}</h2><span className="rounded bg-[#e3f4e1] px-2 py-1 text-[10px] text-[#07623a]">In Stock</span></div><p className="mb-1 mt-2 text-xs text-[#68766d]">250g Pack</p><p className="m-0 text-xs text-[#68766d]">250g (Approx) · Premium Quality</p><span className="mt-3 inline-block rounded-md bg-[#f0e6fb] px-3 py-2 text-[10px] text-[#6932a0]">♧ {cart[product.name]} {cart[product.name]===1?'Pack':'Packs'} · {cart[product.name]*250>=1000?`${cart[product.name]/4} KG`:`${cart[product.name]*250} G`}</span></div><div className="col-span-2 flex flex-wrap items-center justify-between gap-3 sm:col-span-1 sm:justify-end"><div className="mr-2 text-right"><strong className="block text-2xl text-[#075c38]">₹{(product.price*cart[product.name]).toLocaleString('en-IN')}</strong><small className="text-[#68766d]">₹{product.price} × {cart[product.name]}</small></div><button className="grid h-11 w-11 place-items-center rounded-lg border border-[#d7e1d9] bg-white text-[#ed3b2f]" onClick={()=>remove(product.name)} aria-label={`Remove ${product.name}`}><Icon name="trash" className="h-5 w-5"/></button><div className="flex h-11 items-center rounded-lg border border-[#d7e1d9]"><button className="h-full border-0 bg-transparent px-4 text-lg" onClick={()=>change(product.name,-1)} aria-label={`Decrease ${product.name}`}>−</button><b className="min-w-7 text-center">{cart[product.name]}</b><button className="h-full border-0 bg-transparent px-4 text-lg" onClick={()=>change(product.name,1)} aria-label={`Increase ${product.name}`}>+</button></div><button className={`grid h-11 w-11 place-items-center rounded-lg border border-[#d7e1d9] bg-white ${liked.includes(product.name)?'text-[#e22b3d]':'text-[#075c38]'}`} onClick={()=>toggleWish(product.name)} aria-label={`Toggle ${product.name} wishlist`}><Icon name="heart" className={`h-5 w-5 ${liked.includes(product.name)?'fill-current':''}`}/></button></div></article>)}</div>
    <div className="m-4 flex items-center justify-between gap-4 rounded-lg bg-[#eaf6e7] px-5 py-4 text-xs text-[#08613a]"><span>♢ &nbsp; Securely packed and delivered across India</span><a className="font-semibold text-inherit" href="/about">Know More →</a></div>
   </section>

   <aside className="overflow-hidden rounded-xl border border-[#dce5dd] bg-white shadow-[0_7px_24px_#1739230c]"><div className="p-5"><h2 className="m-0 mb-6 flex items-center gap-3 font-serif text-2xl"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#e7f5e3] text-[#087044]"><Icon name="file" className="h-5 w-5"/></span>Order Summary</h2><dl className="m-0 grid grid-cols-2 gap-y-4 text-sm"><dt>Subtotal ({itemCount} {itemCount===1?'item':'items'})</dt><dd className="m-0 text-right font-semibold">₹{subtotal.toLocaleString('en-IN')}</dd><dt>Shipping Charges</dt><dd className="m-0 text-right"><span className="rounded bg-[#ddf3dc] px-2 py-1 font-semibold text-[#087044]">FREE</span></dd><dt>Tax (5%)</dt><dd className="m-0 text-right font-semibold">₹{tax.toLocaleString('en-IN')}</dd></dl><div className="my-6 border-t border-dashed border-[#cdd8ce]"/><div className="flex items-center justify-between"><b className="text-lg">Total Amount</b><strong className="text-3xl text-[#075c38]">₹{total.toLocaleString('en-IN')}</strong></div><div className="mt-4 flex items-center gap-3 rounded-lg bg-[#eaf6e7] px-4 py-3 text-xs font-medium text-[#087044]"><Icon name="leaf" className="h-6 w-6 shrink-0"/>You save with free shipping!</div><div className="mb-[14px] mt-4 flex h-[68px] items-center gap-4 rounded-[7px] bg-gradient-to-r from-[#fff1e0] to-[#fff7ee] px-4"><Icon name="truck" className="h-8 w-8 shrink-0 text-[#ff6e16]"/><span className="flex-1"><b className="block text-sm font-semibold">Estimated Delivery</b><small className="mt-1 block text-xs">3 – 5 Business Days</small></span><span className="text-[26px] font-light text-[#365348]">›</span></div><button className="flex h-[50px] w-full items-center justify-center gap-3 rounded-[7px] border-0 bg-gradient-to-r from-[#087444] to-[#005e37] font-semibold text-white shadow-[0_3px_8px_#075c3820]" onClick={()=>setNotice('Checkout service will be available soon.')}><Icon name="lock" className="h-5 w-5"/>Proceed to Checkout <span className="text-xl">→</span></button><button className="mt-[14px] flex h-[49px] w-full items-center justify-center gap-3 rounded-[7px] border border-[#b9c9bf] bg-white font-semibold text-[#123f31]" onClick={()=>setNotice('Wholesale checkout service will be available soon.')}><Icon name="user" className="h-[22px] w-[22px]"/>Checkout as Wholesale</button></div><div className="grid h-[112px] grid-cols-3 items-center border-t border-[#e1e7e1] px-2">{[['shield','Secure Payments'],['box','Easy Returns'],['headset','24/7 Support']].map(([icon,label])=><div className="text-center" key={label}><span className="mx-auto grid h-11 w-11 place-items-center rounded-full bg-[#e4f3df] text-[#079147]"><Icon name={icon} className="h-6 w-6"/></span><small className="mt-2 block whitespace-nowrap text-[10px] text-[#34483f]">{label}</small></div>)}</div></aside>
   </div>:<section className="my-12 rounded-2xl border border-[#dfe8df] bg-white px-6 py-16 text-center"><span className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-[#e9f6e5] text-[#087044]"><Icon name="cart" className="h-11 w-11"/></span><h2 className="mb-2 mt-5 font-serif text-3xl">Your cart is empty</h2><p className="text-[#607168]">Add your favourite makhana products to get started.</p><a className="mt-5 inline-flex rounded-lg bg-[#05633b] px-7 py-3 font-semibold text-white no-underline" href="/products">Start Shopping</a></section>}
  </main>
  <section className="grid grid-cols-2 gap-4 bg-[#edf7e9] px-[clamp(20px,6vw,90px)] py-6 lg:grid-cols-4">{[['leaf','100% Natural Ingredients','No artificial colors & flavors'],['heart','Hygienically Processed','Clean & safe production'],['box','No Added Preservatives','Pure and healthy snacking'],['truck','Pan India Delivery','Fast & reliable shipping']].map(([icon,label,detail])=><div className="flex items-center justify-center gap-4 border-l border-[#d3dfd3] px-3 first:border-0" key={label}><span className="grid h-14 w-14 shrink-0 place-items-center rounded-full bg-[#dff0d9] text-[#087044]"><Icon name={icon} className="h-7 w-7"/></span><span><b className="block text-sm">{label}</b><small className="mt-1 block text-[11px] text-[#5c6e64]">{detail}</small></span></div>)}</section>
  {notice&&<div className="fixed bottom-5 right-5 z-[1200] rounded-lg bg-[#075d38] px-5 py-3 text-sm text-white shadow-xl" role="status">{notice}</div>}
  <Footer/>
 </div>
}
