import {useState} from 'react'
import StoreNavbar from './StoreNavbar'
import Footer from './Footer'
import './CheckoutPage.css'

const paths={back:'M19 12H5m6-6-6 6 6 6',badge:'M12 2c3 3 6 4 9 4v7c0 5-5 8-9 10-4-2-9-5-9-10V6c3 0 6-1 9-4Zm-4 10 3 3 5-6',pin:'M12 22s7-6 7-13A7 7 0 0 0 5 9c0 7 7 13 7 13Zm0-10a3 3 0 1 1 0-6 3 3 0 0 1 0 6Z',truck:'M2 7h13v11H2zM15 11h4l3 4v3h-7M6 18a2 2 0 1 0 0 4 2 2 0 0 0 0-4Zm12 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4',card:'M2 6h20v13H2zM2 10h20',bank:'M3 10h18M5 10v9m5-9v9m4-9v9m5-9v9M2 21h20M12 3 2 8h20L12 3Z',cash:'M3 6h18v12H3zM7 9a3 3 0 0 1-1 3 3 3 0 0 1 1 3m10-6a3 3 0 0 0 1 3 3 3 0 0 0-1 3M12 9a3 3 0 1 0 0 6 3 3 0 0 0 0-6Z',home:'M3 11.5 12 4l9 7.5V21h-6v-6H9v6H3Z',office:'M5 3h14v18H5zM9 7h2m2 0h2M9 11h2m2 0h2M9 15h2m2 0h2',edit:'m4 20 4-.8L19 8.2 15.8 5 4.8 16 4 20ZM14 6.8l3.2 3.2',trash:'M4 7h16M9 7V4h6v3m-9 0 1 14h10l1-14M10 11v6m4-6v6',plus:'M12 5v14M5 12h14',leaf:'M4 20C0 10 9 4 21 3c0 13-5 20-14 16M3 23 16 9',lock:'M6 10h12v11H6zM9 10V7a3 3 0 0 1 6 0v3',tag:'m20 13-7 7L4 11V4h7l9 9ZM8 8h.01',protein:'M8 21c-3-1-5-4-4-8 0-4 2-7 5-8 2 3 3 5 3 8 0-3 1-6 3-8 3 1 5 4 5 8 0 5-4 8-9 8Z',flask:'M9 3h6M10 3v6l-5 9a2 2 0 0 0 2 3h10a2 2 0 0 0 2-3l-5-9V3M8 15h8',star:'m12 2 3 6 6 .8-4.5 4.5 1 6.7-5.5-3-5.5 3 1-6.7L3 8.8 9 8Z',check:'m5 12 4 4L19 6',farm:'M3 20h18M5 20v-8l7-5 7 5v8M9 20v-5h6v5M4 8c3 0 5-2 5-5-3 0-5 2-5 5Zm16 0c-3 0-5-2-5-5 3 0 5 2 5 5Z',return:'M4 7v6h6M5 12a8 8 0 1 0 2-6',nutrition:'M12 21c-5-2-8-6-8-11 4 0 7 2 8 6 1-4 4-6 8-6 0 6-3 10-8 11Zm0-5V7'}
const iconPaths={...paths,bag:'M5 8h14l-1 13H6L5 8Zm4 0V6a3 3 0 0 1 6 0v2'}
function Icon({name}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={iconPaths[name]}/></svg>}
const highlights=[['leaf','100% Natural'],['protein','Rich in Protein'],['flask','Low in Calories'],['leaf','Gluten Free'],['badge','No Preservatives'],['star','Premium Quality']]
const reasons=[['leaf','100% Natural & Pure','No additives, no preservatives'],['nutrition','Rich in Protein & Fiber','Goodness for your health'],['farm','Farm Fresh Sourcing','Directly from trusted farmers'],['truck','Pan India Delivery','Fast & reliable shipping'],['return','Easy Returns','Hassle-free returns'],['lock','Secure Payments','Your data is always safe']]

export default function CheckoutPage({product,initialQuantity=1,cartCount,wishlistCount}){
 const [quantity,setQuantity]=useState(initialQuantity),[address,setAddress]=useState('home'),[delivery,setDelivery]=useState('standard'),[payment,setPayment]=useState('upi'),[coupon,setCoupon]=useState(false),[agreed,setAgreed]=useState(true),[notice,setNotice]=useState(''),[adding,setAdding]=useState(false)
 const original=product.price+70,discount=original-product.price,deliveryFee=delivery==='express'?49:0,total=product.price*quantity+deliveryFee
 const placeOrder=()=>{if(!agreed){setNotice('Please accept Terms & Conditions first');return}const id=`MG${Date.now().toString().slice(-8)}`;localStorage.setItem('meena-last-order',JSON.stringify({id,product:product.name,quantity,total:total-(coupon?10:0),address,delivery,payment,date:new Date().toISOString()}));history.pushState({},'','/order-success');window.dispatchEvent(new PopStateEvent('popstate'));window.scrollTo(0,0)}
 return <div className="checkout-page"><StoreNavbar cartCount={cartCount} wishlistCount={wishlistCount}/><main className="checkout-main"><header className="checkout-heading"><a href={`/products/${product.name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`}><Icon name="back"/>Back to Product</a><h1>Buy Now</h1><p>Quick, secure and hassle-free checkout</p><div className="checkout-heading-art"><span>Healthy Snacking<br/>Happier You</span><img src="/contact-community-makhana-v2.png" alt="Fresh premium makhana"/></div></header><ol className="checkout-steps">{['Address','Delivery','Payment','Review'].map((step,index)=><li className={index===0?'active':''} key={step}><b>{index+1}</b><span>{step}</span></li>)}</ol>
 <div className="checkout-layout"><div className="checkout-sections"><section><h2><b>1</b><img className="checkout-title-bag" src="/checkout-bag-icon.png" alt=""/>Product Details</h2><div className="checkout-product"><figure className="checkout-product-art"><img className="product-bowl" src="/contact-community-makhana-v2.png" alt=""/><img className="product-pack" src={product.image} alt={product.name}/></figure><div><h3>{product.name} Makhana</h3><p>250 g | Pack of {quantity}</p><div className="checkout-rating" aria-label="Rated 4.8 out of 5"><span>★★★★★</span><b>4.8</b><small>(12,856 reviews)</small></div><strong>₹{product.price*quantity}</strong> <del>₹{original*quantity}</del> <span>{Math.round(discount/original*100)}% OFF</span><small>₹{(product.price/250).toFixed(2)} / g</small></div><div className="checkout-qty"><button onClick={()=>setQuantity(Math.max(1,quantity-1))} aria-label="Decrease quantity">−</button><b>{quantity}</b><button onClick={()=>setQuantity(quantity+1)} aria-label="Increase quantity">+</button><small>● &nbsp;In Stock</small></div></div><div className="checkout-chips">{highlights.slice(0,4).map(([icon,label])=><span key={label}><Icon name={icon}/>{label}</span>)}</div></section>
  <section><h2><b>2</b><Icon name="pin"/>Delivery Address <button onClick={()=>setNotice('Saved addresses refreshed')}>Saved Addresses⌄</button></h2><div className="address-grid"><button className={address==='home'?'selected':''} onClick={()=>setAddress('home')}><Icon name="home"/><span><b>Raj Vardhan Singh <small>Home</small></b><p>Ward No. 5, Purnea, Bihar - 854302<br/>+91 98765 43210</p><i><Icon name="edit"/>Edit &nbsp; | &nbsp; <Icon name="trash"/>Delete</i></span></button><button className={address==='office'?'selected':''} onClick={()=>setAddress('office')}><Icon name="office"/><span><b>Office</b><p>RK University, Kasturba Road<br/>Rajkot, Gujarat - 360020<br/>+91 98765 43210</p><i><Icon name="edit"/>Edit &nbsp; | &nbsp; <Icon name="trash"/>Delete</i></span></button></div><button className="add-address" onClick={()=>setAdding(!adding)}><Icon name="plus"/>Add New Address</button>{adding&&<form className="address-form" onSubmit={e=>{e.preventDefault();setAdding(false);setNotice('New address saved')}}><input required placeholder="Full name"/><input required placeholder="Phone number"/><input required placeholder="Address and PIN code"/><button>Save Address</button></form>}</section>
  <section><h2><b>3</b><Icon name="truck"/>Delivery Options</h2><p className="section-note">Choose how you want to receive your order</p><div className="delivery-options"><button className={delivery==='standard'?'selected':''} onClick={()=>setDelivery('standard')}><Icon name="truck"/><span><b>Standard Delivery</b><strong>3 - 5 Business Days</strong><small>Delivery by 18 - 21 Sep</small></span><em>FREE</em></button><button className={delivery==='express'?'selected':''} onClick={()=>setDelivery('express')}><Icon name="truck"/><span><b>Express Delivery</b><strong>1 - 2 Business Days</strong><small>Delivery by 15 - 16 Sep</small></span><em>₹49</em></button></div><div className="free-banner"><Icon name="leaf"/><span><b>Free delivery on orders above ₹499</b><small>Add more products to save on delivery charges!</small></span></div></section>
  <section><h2><b>4</b><Icon name="card"/>Payment Method</h2><p className="section-note">Choose a payment method</p><div className="payment-options">{[['upi','UPI','Google Pay / PhonePe / Paytm / BHIM','UPI'],['card','Card','Debit / Credit Card','card'],['bank','Net Banking','All Banks','bank'],['cash','Cash on Delivery','Pay when you receive','cash']].map(([id,title,text,icon])=><button className={payment===id?'selected':''} onClick={()=>setPayment(id)} key={id}><span className={`payment-symbol ${id}`}>{id==='upi'?<strong>UPI</strong>:<Icon name={icon}/>}</span><b>{title}</b><small>{text}</small>{payment===id&&<i className="payment-selected"><Icon name="check"/></i>}</button>)}</div><div className="secure-pay"><Icon name="badge"/><span><b>100% Secure Payments</b><small>Your payment information is encrypted and safe with us.</small></span><p><i className="gpay">G Pay</i><i className="phonepe">PhonePe</i><i className="paytm">Paytm</i><i className="visa">VISA</i><i className="master"><b/><b/></i></p></div><label className="terms"><input type="checkbox" checked={agreed} onChange={e=>setAgreed(e.target.checked)}/>I agree to the <a href="#terms">Terms &amp; Conditions</a> and <a href="#privacy">Privacy Policy</a></label></section>
  <section className="checkout-highlights"><h2><Icon name="star"/>Product Highlights</h2><div>{highlights.map(([icon,label])=><span key={label}><i><Icon name={icon}/></i><small>{label}</small></span>)}</div></section></div>
  <aside><section className="order-summary"><h2>Order Summary <small>({quantity} Item)</small><button onClick={()=>setNotice('Order editing enabled')}><Icon name="edit"/>Edit</button></h2><div className="summary-product"><img src={product.image} alt=""/><div><b>{product.name} Makhana</b><span>250 g | Pack of {quantity}</span><strong>₹{product.price*quantity} <del>₹{original*quantity}</del></strong></div><b>Qty: {quantity}</b></div><button className="apply-coupon" onClick={()=>setCoupon(!coupon)}><Icon name="tag"/><span><b>{coupon?'Coupon SAVE10 Applied':'Apply Coupon'}</b><small>{coupon?'You saved extra ₹10':'Get extra discount'}</small></span>›</button><dl><dt>Item Total</dt><dd>₹{original*quantity}</dd><dt>Discount</dt><dd className="saving">- ₹{discount*quantity+(coupon?10:0)}</dd><dt>Delivery Charges</dt><dd className={deliveryFee?'':'saving'}>{deliveryFee?`₹${deliveryFee}`:'FREE'}</dd></dl><div className="summary-total"><b>Total Amount <small>(Incl. of all taxes)</small></b><strong>₹{total-(coupon?10:0)}</strong></div><div className="saving-box">🐷 <span><b>You are saving ₹{discount*quantity+(coupon?10:0)}</b><small>Yay! Great choice!</small></span></div></section><section className="checkout-reasons"><h2>Why Choose Meena Green?</h2>{reasons.map(([icon,title,text])=><div key={title}><span><Icon name={icon}/></span><p><b>{title}</b><small>{text}</small></p></div>)}</section><section className="nature-card"><h2>Goodness<br/>from Nature <Icon name="leaf"/></h2><img src="/contact-community-makhana-v2.png" alt="Bowl of premium makhana"/><div>{['Natural','Nutritious','Farm Fresh','Trusted'].map(label=><span key={label}><Icon name="leaf"/><small>{label}</small></span>)}</div></section></aside></div></main>
 <div className="checkout-sticky"><img src={product.image} alt=""/><p><b>{product.name} Makhana</b><small>250 g | Pack of {quantity}</small></p><strong>₹{total-(coupon?10:0)}</strong><div><button onClick={()=>setQuantity(Math.max(1,quantity-1))}>−</button><b>{quantity}</b><button onClick={()=>setQuantity(quantity+1)}>+</button></div><button className="place-order" onClick={placeOrder}><Icon name="lock"/>Place Order &nbsp; ₹{total-(coupon?10:0)} →</button><small><Icon name="badge"/>Safe &amp; Secure Checkout</small></div>{notice&&<div className="checkout-toast" role="status">{notice}<button onClick={()=>setNotice('')}>×</button></div>}<Footer/></div>
}
