import {useState} from 'react'
import './Footer.css'
const paths={link:'M10 13a5 5 0 0 0 7 0l4-4a5 5 0 0 0-7-7l-3 3M14 11a5 5 0 0 0-7 0l-4 4a5 5 0 0 0 7 7l3-3',box:'m3 6 9-4 9 4v12l-9 4-9-4V6Zm0 0 9 5 9-5M12 11v11M7 4l10 5',headset:'M3 14v-3a9 9 0 0 1 18 0v3M3 12h4v8H3zM17 12h4v8h-4zM20 20c0 2-4 2-8 2',pin:'M12 22S4 15 4 9a8 8 0 0 1 16 0c0 6-8 13-8 13ZM12 6a3 3 0 1 0 0 6 3 3 0 0 0 0-6',phone:'M5 3h4l2 5-3 2a17 17 0 0 0 6 6l2-3 5 2v4c0 2-2 3-4 2C9 19 5 15 3 7c-1-2 0-4 2-4Z',mail:'M2 4h20v16H2zM2 5l10 8L22 5',clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18Zm0 3v6l5 3',leaf:'M4 20C-1 10 9 4 21 3c0 13-5 20-14 16M3 23 16 9',shield:'M12 2c3 3 6 4 9 4v7c0 5-5 8-9 10-4-2-9-5-9-10V6c3 0 6-1 9-4Zm-5 10 4 4 6-7',truck:'M2 5h13v13H2zM15 10h4l4 5v3h-8M5 18a2 2 0 1 0 0 4 2 2 0 0 0 0-4Zm14 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4',heart:'M12 21 3 12C-3 4 7-2 12 5c5-7 15-1 9 7Z'}
function Glyph({name}){return <svg viewBox="0 0 24 24" width="24" height="24" fill={name==='heart'?'currentColor':'none'} stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]}/></svg>}
function LinkColumn({title,icon,items}){return <div className="footer-column"><h3><Glyph name={icon}/>{title}</h3><ul>{items.map(([label,href])=><li key={label}><a href={href}>{label}<span aria-hidden="true">›</span></a></li>)}</ul></div>}
export default function Footer(){
 const [notice,setNotice]=useState('')
 return <footer className="meena-footer" id="contact">
  <div className="footer-main">
   <div className="footer-identity"><img className="footer-logo" src="/meena-logo-premium.png" alt="Meena Green"/><h2>Healthy Snacking<br/>Happier You <Glyph name="leaf"/></h2><p>Premium quality makhana for a healthier and happier life.</p><div className="footer-socials">{[['Facebook','footer-facebook.png'],['Instagram','footer-instagram.png'],['YouTube','footer-youtube.png']].map(([name,image])=><button key={name} aria-label={name} onClick={()=>setNotice(`${name} page link is coming soon.`)}><img src={'/'+image} alt=""/></button>)}</div><p className="footer-nature">Goodness from Nature <Glyph name="leaf"/></p></div>
   <LinkColumn title="Quick Links" icon="link" items={ [['Home','#home'],['Products','#products'],['About Us','#about'],['Retail Mode','#modes'],['Wholesale Mode','#modes'],['Contact Us','#contact']]}/>
   <LinkColumn title="Our Products" icon="box" items={ [['Plain Makhana','#products'],['Roasted Makhana','#products'],['Flavoured Makhana','#products'],['Gift Packs','#products'],['All Products','#products']]}/>
   <div className="footer-column"><h3><Glyph name="headset"/>Customer Care</h3><ul>{['Help Center','Shipping Policy','Return Policy','Order Tracking','FAQs','Privacy Policy'].map(label=><li key={label}><button onClick={()=>setNotice(`${label}: Please contact care@meenagreen.in for assistance. This page is not available yet.`)}>{label}<span aria-hidden="true">›</span></button></li>)}</ul></div>
   <div className="footer-column footer-contact"><h3><Glyph name="pin"/>Contact Us</h3><a href="tel:+919876543210"><Glyph name="phone"/><span>+91 98765 43210</span></a><a href="mailto:care@meenagreen.in"><Glyph name="mail"/><span>care@meenagreen.in</span></a><p><Glyph name="pin"/><span>Purnea, Bihar, India</span></p><p><Glyph name="clock"/><span>Mon – Sat: 9AM – 7PM<small>(Sunday Closed)</small></span></p></div>
  </div>
  <div className="footer-updates"><div className="footer-update-label"><Glyph name="mail"/><div><b>Stay Updated</b><small>Get latest offers, new products and health tips.</small></div></div><form onSubmit={e=>{e.preventDefault();setNotice('Email subscriptions are not connected yet. Please contact care@meenagreen.in for updates.')}}><label className="footer-email"><Glyph name="mail"/><input type="email" required placeholder="Enter your email address" aria-label="Email address for updates"/></label><button>Subscribe</button></form><div className="footer-payments"><b>We Accept</b><img src="/footer-visa.png" alt="Visa"/><span className="payment-upi">UPI</span></div></div>
  {notice&&<div className="footer-notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss message">×</button></div>}
  <div className="footer-bottom"><p>© {new Date().getFullYear()} Meena Green. All rights reserved.</p><div className="footer-mini-promises">{[['leaf','100% Natural'],['shield','Hygienically Processed'],['leaf','No Added Preservatives'],['truck','Pan India Delivery']].map(([icon,label])=><span key={label}><Glyph name={icon}/>{label}</span>)}</div><p className="made-with">Made with <Glyph name="heart"/> for a Healthier India <Glyph name="leaf"/></p></div>
 </footer>
}
