import {useState} from 'react'
import StoreNavbar from './StoreNavbar'
import AccountSidebar from './AccountSidebar'
import {getOrders} from './ordersData'
import './OrderDetailsPage.css'

const paths={back:<path d="m15 18-6-6 6-6"/>,check:<path d="m6 12 4 4 8-9"/>,receipt:<><rect x="5" y="3" width="14" height="18" rx="2"/><path d="m9 3 1 2 2-2 2 2 1-2M9 10h6m-6 4h4"/></>,package:<><path d="m3 7 9-4 9 4-9 4Z"/><path d="m3 7 9 4 9-4v10l-9 4-9-4V7Zm9 4v10"/></>,truck:<><path d="M3 6h11v11H3zM14 10h4l3 4v3h-7z"/><circle cx="7" cy="19" r="2"/><circle cx="18" cy="19" r="2"/></>,home:<path d="m3 11 9-8 9 8v10h-6v-6H9v6H3Z"/>,pin:<><path d="M19 10c0 5-7 12-7 12S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/></>,cart:<><path d="M3 4h2l2 10h11l2-7H6M9 20h.01M17 20h.01"/></>,x:<><circle cx="12" cy="12" r="9"/><path d="m9 9 6 6m0-6-6 6"/></>,refund:<><path d="M4 7h11a5 5 0 0 1 0 10H8"/><path d="m8 3-4 4 4 4M12 10h4m-2-2v4"/></>,warning:<><path d="m12 3 10 18H2L12 3Z"/><path d="M12 9v5m0 3h.01"/></>,card:<><rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 10h18m-14 5h3"/></>,document:<><path d="M6 2h8l4 4v16H6Z"/><path d="M14 2v5h5M9 12h6m-6 4h6"/></>,download:<><path d="M12 3v12m-4-4 4 4 4-4M4 20h16"/></>,headset:<><path d="M4 14v-2a8 8 0 0 1 16 0v2M4 14h3v6H4Zm16 0h-3v6h3Z"/></>,chevron:<path d="m9 5 7 7-7 7"/>,shield:<><path d="M12 3 20 6v6c0 5-3.4 8-8 10-4.6-2-8-5-8-10V6l8-3Z"/><path d="m8.5 12 2.3 2.3 4.8-5"/></>}
function Icon({name}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>}
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
const go=path=>{history.pushState({},'',path);window.dispatchEvent(new PopStateEvent('popstate'));window.scrollTo({top:0,behavior:'smooth'})}

export default function OrderDetailsPage({orderId}){
 const [orders,setOrders]=useState(getOrders),[cart,setCart]=useState(()=>read('meena-cart',{})),[action,setAction]=useState(null),[liveOpen,setLiveOpen]=useState(false),[notice,setNotice]=useState('')
 const order=orders.find(item=>String(item.id)===String(orderId))
 const wishlist=read('meena-wishlist',[]),notifications=read('meena-notifications',[]),notificationCount=Array.isArray(notifications)?notifications.filter(item=>item.unread).length:0
 const toast=message=>{setNotice(message);window.setTimeout(()=>setNotice(''),2600)}
 if(!order)return <><StoreNavbar wishlistCount={wishlist.length}/><main className="order-detail-page"><div className="order-detail-shell"><AccountSidebar active="My Orders" wishlistCount={wishlist.length} notificationCount={notificationCount}/><section className="order-not-found"><Icon name="package"/><h1>Order not found</h1><p>This order may have been removed or is no longer available.</p><button onClick={()=>go('/orders')}>Back to My Orders</button></section></div></main></>
 const stage=order.status==='Delivered'?4:order.status==='Out for Delivery'?3:order.status==='Shipped'?2:order.status==='Processing'?1:0
 const paid=order.amount*order.qty
 const buyAgain=()=>{const next={...cart,[order.name]:(cart[order.name]||0)+order.qty};setCart(next);localStorage.setItem('meena-cart',JSON.stringify(next));toast(`${order.name} added to your cart.`)}
 const cancelOrder=()=>{const next=orders.map(item=>item.id===order.id?{...item,status:'Cancelled'}:item);setOrders(next);localStorage.setItem('meena-order-history',JSON.stringify(next));setAction(null);toast('Order cancelled successfully.');window.setTimeout(()=>go('/orders'),900)}
 const downloadInvoice=()=>{const text=`MEENA GREEN\nInvoice for Order #${order.id}\n${order.name} — ${order.variant}\nQuantity: ${order.qty}\nTotal Paid: ₹${paid}\nPayment: ${order.payment}\n`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const link=document.createElement('a');link.href=url;link.download=`Meena-Green-${order.id}-invoice.txt`;link.click();URL.revokeObjectURL(url);toast('Invoice downloaded.')}
 const openAction=type=>{if(type==='cancel'&&['Delivered','Cancelled','Returned'].includes(order.status)){toast('This order is no longer eligible for cancellation.');return}setAction(type)}
 const completeRequest=()=>{const labels={return:'Return / replacement request submitted.',refund:'Refund request submitted.',issue:'Issue reported to our support team.'};toast(labels[action]);setAction(null)}
 const cartCount=Object.values(cart).reduce((sum,value)=>sum+value,0)
 return <><StoreNavbar active="account" wishlistCount={wishlist.length||3} cartCount={cartCount||2}/><main className="order-detail-page"><div className="order-detail-shell"><AccountSidebar active="My Orders" wishlistCount={wishlist.length||3} notificationCount={notificationCount}/><section className="order-detail-main">
  <button className="order-detail-back" onClick={()=>go('/orders')}><Icon name="back"/>My Orders</button>
  <header className="order-detail-heading"><div><h1>Order Details</h1><p>Order #{order.id}<span/>Placed on {order.date}, 10:24 AM</p></div><div className={`order-status-badge ${order.status.toLowerCase().replaceAll(' ','-')}`}><i><Icon name={order.status==='Delivered'?'check':'package'}/></i><b>{order.status==='Shipped'?'On the way':order.status}</b><small>{order.status==='Delivered'?'Delivered successfully':'Expected delivery in 2–4 working days'}</small></div></header>
  <section className="order-detail-card tracking-card"><h2>Order Tracking</h2><p>Your order is {order.status.toLowerCase()}. {order.status==='Delivered'?'We hope you enjoy your makhana!':'We will keep you updated at every step.'}</p><DetailTimeline stage={stage} order={order}/><div className="tracking-alert"><i><Icon name="truck"/></i><span><b>{order.status==='Delivered'?'Your order was delivered':'Your order is in transit'}</b><small>{order.status==='Delivered'?'Package delivered to your saved address.':'Your package is moving through our delivery network.'}</small></span><button onClick={()=>setLiveOpen(value=>!value)}>{liveOpen?'Hide Live Location':'View Live Location'}<Icon name="chevron"/></button></div>{liveOpen&&<div className="live-location"><div><span/><span/><span/></div><b>Package route</b><p>Patna Sorting Center → Purnea Delivery Hub → Your address</p></div>}</section>
  <section className="order-detail-card product-detail-card"><h2>Product Details</h2><div><img src={order.image} alt={order.name}/><span><b>{order.name}</b><p>{order.variant}</p><strong>₹{order.amount}</strong><small>Qty: {order.qty}</small><em>Sold by: Meena Green</em></span><button onClick={buyAgain}><Icon name="cart"/>Buy Again</button></div></section>
  <section className="order-detail-card order-help-card"><h2>Need Help with this Order?</h2><p>You can cancel, return or request help from here.</p><div>{[['cancel','x','Cancel Order','Cancel before delivery'],['return','package','Return / Replace','Return after delivery'],['refund','refund','Request Refund','Check refund status'],['issue','warning','Report an Issue','Tell us what went wrong']].map(([type,icon,label,desc])=><button key={type} className={type} onClick={()=>openAction(type)}><i><Icon name={icon}/></i><b>{label}</b><small>{desc}</small></button>)}</div></section>
  <div className="order-detail-grid"><section className="order-detail-card delivery-card"><header><h2>Delivery Address</h2><button onClick={()=>go('/addresses')}>Change</button></header><div><Icon name="pin"/><span><b>Raj Vardhan Singh</b><p>H.No. 221, Ward No. 5, Near Gandhi Chowk<br/>Purnea, Bihar – 854301</p><small>Mobile: +91 98765 43210</small></span></div></section><section className="order-detail-card summary-card"><h2>Order Summary</h2><p><span>Item Total ({order.qty} items)</span><b>₹{paid}</b></p><p><span>Delivery Charges</span><b>₹0</b></p><p><span>Discount</span><b className="green">- ₹0</b></p><strong><span>Total Paid</span><b>₹{paid}</b></strong><small>Paid via {order.payment}</small></section></div>
  <section className="order-detail-card payment-card"><h2>Payment Information</h2><div><i><Icon name="card"/></i><span><b>Paid via {order.payment}</b><p>Transaction ID: T250508102345678</p></span><strong>₹{paid}<em>Payment Successful</em></strong></div></section>
  <div className="order-detail-grid bottom"><section className="order-detail-card info-card"><i><Icon name="document"/></i><div><h2>Order Information</h2><p><span>Order Number</span><b>{order.id}</b></p><p><span>Order Date</span><b>{order.date}, 10:24 AM</b></p><p><span>Seller</span><b>Meena Green</b></p><button onClick={downloadInvoice}><Icon name="download"/>Download Invoice</button></div></section><section className="order-detail-card more-help-card"><i><Icon name="headset"/></i><div><h2>Need More Help?</h2><p>Visit our Help &amp; Support section for more assistance.</p><button onClick={()=>go('/support')}>Contact Support<Icon name="chevron"/></button></div></section></div>
 </section></div></main>
 {action&&<div className="order-action-backdrop"><section className="order-action-modal" role="dialog" aria-modal="true" aria-labelledby="order-action-title"><i><Icon name={action==='cancel'?'x':action==='issue'?'warning':action==='refund'?'refund':'package'}/></i><h2 id="order-action-title">{action==='cancel'?'Cancel this order?':action==='return'?'Return or replace item':action==='refund'?'Request a refund':'Report an issue'}</h2><p>{action==='cancel'?'This action will move the order to your cancelled orders.':'Our support team will review your request and contact you shortly.'}</p>{action!=='cancel'&&<textarea aria-label="Request details" placeholder="Tell us a little more about your request…"/>}<div><button onClick={()=>setAction(null)}>Go Back</button><button className={action==='cancel'?'danger':''} onClick={action==='cancel'?cancelOrder:completeRequest}>{action==='cancel'?'Cancel Order':'Submit Request'}</button></div></section></div>}
 {notice&&<div className="order-detail-toast" role="status"><Icon name="check"/>{notice}</div>}</>
}

function DetailTimeline({stage,order}){const steps=[['Order Placed','receipt'],['Confirmed','check'],['Shipped','package'],['Out for Delivery','truck'],['Delivered','home']];const dates=[order.times?.[0]||'08 May\n10:24 AM','08 May\n11:05 AM',order.times?.[1]||'—',order.times?.[2]||'—',order.times?.[3]||'—'];return <div className="detail-timeline" style={{'--detail-progress':stage/4}}>{steps.map(([label,icon],index)=><div className={index<=stage?'done':''} key={label}><i><Icon name={index<stage?'check':icon}/></i><b>{label}</b><small>{dates[index]}</small></div>)}</div>}
