import {useState} from 'react'
import StoreNavbar from './StoreNavbar'
import Footer from './Footer'
import './OrderSuccessPage.css'

const icons={check:'m5 12 4 4L19 6',pin:'M12 22s7-6 7-13A7 7 0 0 0 5 9c0 7 7 13 7 13Zm0-10a3 3 0 1 1 0-6 3 3 0 0 1 0 6Z',calendar:'M4 5h16v16H4zM8 2v6m8-6v6M4 10h16',card:'M3 6h18v13H3zM3 10h18',box:'m3 7 9-4 9 4-9 4-9-4Zm0 0v10l9 4 9-4V7m-9 4v10',mail:'M3 5h18v14H3zm0 1 9 7 9-7',bell:'M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9m-8 12h4',truck:'M2 7h13v11H2zM15 11h4l3 4v3h-7M6 18a2 2 0 1 0 0 4 2 2 0 0 0 0-4Zm12 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4',home:'M3 11 12 4l9 7v10h-6v-6H9v6H3z',shield:'M12 2c3 3 6 4 9 4v7c0 5-5 8-9 10-4-2-9-5-9-10V6c3 0 6-1 9-4Z',headset:'M4 14v-2a8 8 0 0 1 16 0v2M4 14h3v6H4zm16 0h-3v6h3',star:'m12 2 3 6 6 1-4.5 4 1 7-5.5-3-5.5 3 1-7L3 9l6-1z',cart:'M3 4h2l2 11h11l2-8H6m3 13h.01M17 20h.01',leaf:'M4 20C1 10 9 4 21 3c0 13-6 20-14 16M3 23 16 9'}
function Icon({name}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={icons[name]}/></svg>}
const go=path=>{history.pushState({},'',path);window.dispatchEvent(new PopStateEvent('popstate'));window.scrollTo(0,0)}
export default function OrderSuccessPage({order,product,recommendations,cartCount,wishlistCount,onAdd}){
 const [reviewOpen,setReviewOpen]=useState(false),[rating,setRating]=useState(4),[review,setReview]=useState(''),[photoName,setPhotoName]=useState(''),[reviewSent,setReviewSent]=useState(false)
 const now=order.date?new Date(order.date):new Date(),qty=Number(order.quantity)||1,total=Number(order.total)||product.price*qty,original=(product.price+70)*qty,discount=original-total
 const date=now.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}),time=now.toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'}),delivery=new Date(now.getTime()+(order.delivery==='express'?2:5)*86400000).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})
 const id=order.id||'MG202601145678'
 return <div className="success-page"><StoreNavbar cartCount={cartCount} wishlistCount={wishlistCount}/><main className="success-main"><button className="success-back" onClick={()=>window.history.length>1?history.back():go('/products')}><span aria-hidden="true">←</span> Back</button><section className="success-hero"><div className="success-note">Healthy Snacking<br/>Happier You ♡</div><span className="success-check"><Icon name="check"/></span><h1>Order Placed Successfully!</h1><h2>Thank you for choosing Meena Green.</h2><p>Your order has been received and is being processed. We’ll notify you once it is shipped.</p><img src="/contact-community-makhana-v2.png" alt="Premium makhana bowl"/></section>
 <section className="success-facts">{[["pin","Order ID",`#${id}`,`${date}, ${time}`],["calendar","Estimated Delivery",delivery,order.delivery==='express'?'1 – 2 Business Days':'3 – 5 Business Days'],["card","Payment Method",order.payment==='cash'?'Cash on Delivery':order.payment==='card'?'Card':order.payment==='bank'?'Net Banking':'UPI / Google Pay','Payment Successful'],["box","Order Status","Confirmed","We’ll keep you updated"]].map(([icon,label,value,note])=><div key={label}><i><Icon name={icon}/></i><span><small>{label}</small><b>{value}</b><em>{note}</em></span></div>)}</section>
 <div className="success-contact"><section><h2><Icon name="pin"/>Delivery Address <button onClick={()=>go('/addresses')}>Change</button></h2><b>Raj Vardhan Singh</b><p>Ward No. 5, Purnea, Bihar - 854302<br/>+91 98765 43210</p></section><section><h2><Icon name="mail"/>Contact &amp; Updates</h2><p>Updates will be sent to:<br/><b>rajvardhan@gmail.com</b><br/><b>+91 98765 43210</b></p><aside><Icon name="bell"/><b>Get real-time updates<br/>on your order</b><a href="https://wa.me/919876543210">Track on WhatsApp</a></aside></section></div>
 <section className="success-order" id="success-order-summary"><h2><Icon name="box"/>Order Summary</h2><div className="success-order-grid"><img src={product.image} alt={product.name}/><div><b>{product.name} Makhana</b><small>250 g | Pack of {qty}</small><strong>₹{total} <del>₹{original}</del> <em>{Math.round(discount/original*100)}% OFF</em></strong><p><span>✓ 100% Natural</span><span>✓ No Preservatives</span></p></div><b>Qty: {qty}</b><dl><dt>Item Total</dt><dd>₹{original}</dd><dt>Discount</dt><dd>- ₹{discount}</dd><dt>Delivery Charges</dt><dd>FREE</dd><strong>Total Paid</strong><strong>₹{total}</strong></dl></div></section>
 <section className="success-tracking"><h2><Icon name="truck"/>Order Tracking <small>Expected delivery by {delivery}</small></h2><div>{[['check','Order Placed',`${date}, ${time}`],['check','Confirmed',`${date}, ${time}`],['box','Packed','Preparing your order'],['truck','Shipped','Yet to ship'],['home','Delivered',`Expected by ${delivery}`]].map(([icon,label,note],index)=><span className={index<2?'done':''} key={label}><i><Icon name={icon}/></i><b>{label}</b><small>{note}</small></span>)}</div></section>
 <div className="success-actions"><button onClick={()=>{setReviewSent(false);setReviewOpen(true)}}><Icon name="box"/>Review Order</button><button onClick={()=>go('/products')}><Icon name="cart"/>Continue Shopping</button></div>
 <section className="success-benefits">{[['shield','Secure Payments','100% Safe & Secure'],['truck','Fast Delivery','Across India'],['headset','24/7 Support','We’re here to help'],['star','Quality Assured','Premium Quality Products']].map(([icon,title,note])=><div key={title}><i><Icon name={icon}/></i><span><b>{title}</b><small>{note}</small></span></div>)}</section>
 <section className="success-recommend"><h2>You Might Also Like <a href="/products">See All Products →</a></h2><div>{recommendations.map(item=><article key={item.name}><img src={item.image} alt={item.name}/><b>{item.name} Makhana</b><small>250 g</small><strong>₹{item.price}</strong><button onClick={()=>onAdd(item.name)}><Icon name="cart"/>Add to Cart</button></article>)}</div></section>{reviewOpen&&<div className="review-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setReviewOpen(false)}}><section className="review-modal" role="dialog" aria-modal="true" aria-labelledby="review-modal-title"><button className="review-close" onClick={()=>setReviewOpen(false)} aria-label="Close review">×</button>{reviewSent?<div className="review-thanks"><span><Icon name="check"/></span><h2>Thank You!</h2><p>Your review has been submitted successfully.</p><button onClick={()=>setReviewOpen(false)}>Done</button></div>:<><header><i><Icon name="star"/></i><div><h2 id="review-modal-title">Review Your Order</h2><p>Share your experience and help us serve you better!</p></div></header><div className="review-product"><img src={product.image} alt={product.name}/><div><b>{product.name} Makhana</b><small>250 g</small><span>PREMIUM QUALITY</span></div></div><div className="review-rating"><label>Your Rating</label><strong>{rating}/5</strong><div>{[1,2,3,4,5].map(value=><button type="button" className={value<=rating?'active':''} onClick={()=>setRating(value)} key={value} aria-label={`${value} star rating`}>★</button>)}</div><small>{rating===5?'Excellent!':rating===4?'Great!':rating===3?'Good':rating===2?'Fair':'Needs improvement'}</small></div><label className="review-copy">Your Review<textarea value={review} onChange={e=>setReview(e.target.value)} placeholder="How was your experience with this product?" maxLength="500"/><small>{review.length}/500</small></label><label className="review-photo"><Icon name="box"/><span><b>{photoName||'Add Photos (Optional)'}</b><small>Upload up to 3 photos (JPG, PNG)</small></span><input type="file" accept="image/png,image/jpeg" onChange={e=>setPhotoName(e.target.files?.[0]?.name||'')} hidden/></label><footer><button type="button" onClick={()=>setReviewOpen(false)}>Cancel</button><button type="button" disabled={!review.trim()} onClick={()=>{const saved=JSON.parse(localStorage.getItem('meena-product-reviews')||'[]');localStorage.setItem('meena-product-reviews',JSON.stringify([...saved,{orderId:id,product:product.name,rating,review,photoName,date:new Date().toISOString()}]));setReviewSent(true)}}>➤ Submit Review</button></footer><p className="review-note">Your review will be visible to other customers after moderation.</p></>}</section></div>}</main><Footer/></div>
}
