import {useState} from 'react'
import StoreNavbar from './StoreNavbar'
import Footer from './Footer'
import './ProductDetailsPage.css'

const paths={home:'M3 11.5 12 4l9 7.5V21H15v-6H9v6H3Z',heart:'M20.8 5.6a5.2 5.2 0 0 0-7.4 0L12 7l-1.4-1.4a5.2 5.2 0 1 0-7.4 7.4L12 21l8.8-8a5.2 5.2 0 0 0 0-7.4Z',share:'M18 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6ZM6 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm12 7a3 3 0 1 0 0-6 3 3 0 0 0 0 6ZM8.6 10.5l6.8-4M8.6 13.5l6.8 4',cart:'M3 4h2l2 10a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2l2-7H6m4 13h.01M17 20h.01',bolt:'m13 2-8 12h7l-1 8 8-12h-7Z',tag:'m20 13-7 7L4 11V4h7l9 9ZM8 8h.01',gift:'M20 12v9H4v-9M2 7h20v5H2zM12 7H7.5A2.5 2.5 0 1 1 12 4.5V7Zm0 0h4.5A2.5 2.5 0 1 0 12 4.5V7Zm0 0v14',truck:'M2 7h13v11H2zM15 11h4l3 4v3h-7M6 18a2 2 0 1 0 0 4 2 2 0 0 0 0-4Zm12 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4',return:'M8 7 3 12l5 5M3 12h10a7 7 0 0 1 7 7',leaf:'M4 20C0 10 9 4 21 3c0 13-5 20-14 16M3 23 16 9',shield:'M12 2c3 3 6 4 9 4v7c0 5-5 8-9 10-4-2-9-5-9-10V6c3 0 6-1 9-4Zm-5 10 4 4 6-7',protein:'M8 21c-3-1-5-4-4-8 0-4 2-7 5-8 2 3 3 5 3 8 0-3 1-6 3-8 3 1 5 4 5 8 0 5-4 8-9 8Z',flask:'M9 3h6M10 3v6l-5 9a2 2 0 0 0 2 3h10a2 2 0 0 0 2-3l-5-9V3M8 15h8',pin:'M12 22s7-6 7-13A7 7 0 0 0 5 9c0 7 7 13 7 13Zm0-10a3 3 0 1 1 0-6 3 3 0 0 1 0 6Z',calendar:'M3 6h18v15H3zM7 3v6M17 3v6M3 10h18',card:'M2 6h20v13H2zM2 10h20',file:'M5 2h10l4 4v16H5zM14 2v5h5M8 12h8M8 16h8',star:'m12 2 3 6 6 .8-4.5 4.5 1 6.7-5.5-3-5.5 3 1-6.7L3 8.8 9 8Z',thumb:'M7 10v11H3V10h4Zm0 9h10a2 2 0 0 0 2-1.6l1.5-7A2 2 0 0 0 18.5 8H14l1-4c.3-2-2-3-3-1L7 10',check:'m5 12 4 4L19 6'}
function Icon({name}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]}/></svg>}
const features=[['leaf','100% Natural','No additives'],['protein','Rich in Protein','Good for health'],['leaf','Low in Calories','Guilt-free snacking'],['shield','Gluten Free','Safe for all'],['flask','No Preservatives','Pure and clean'],['star','Premium Quality','Farm to your table']]
const reviews=[['S','Sunil Kumar','Very tasty and fresh makhana. Quality is excellent and packaging is also good. Highly recommended!'],['P','Priya Sharma','Good product, crunchy and healthy. Loved the natural taste. Will buy again.'],['A','Amit Verma','Best makhana I have ever had. 100% natural and fresh. Worth the price.']]

export default function ProductDetailsPage({product,cartCount,wishlistCount,liked,onToggleLike,onAdd}){
 const [quantity,setQuantity]=useState(1),[view,setView]=useState(0),[notice,setNotice]=useState(''),[editPin,setEditPin]=useState(false),[pin,setPin]=useState('854302'),[reviewOpen,setReviewOpen]=useState(false)
 const original=product.price+70,discount=Math.round((original-product.price)/original*100)
 const views=['product','lifestyle','closeup']
 const add=()=>{onAdd(quantity);setNotice(`${quantity} pack${quantity>1?'s':''} added to cart`)}
 const buy=()=>{sessionStorage.setItem('meena-checkout-product',JSON.stringify({name:product.name,quantity}));history.pushState({},'','/checkout');window.dispatchEvent(new PopStateEvent('popstate'));window.scrollTo(0,0)}
 const share=async()=>{const url=location.href;try{await navigator.clipboard.writeText(url);setNotice('Product link copied')}catch{setNotice(url)}}
 return <div className="detail-page"><StoreNavbar active="products" cartCount={cartCount} wishlistCount={wishlistCount}/><main className="detail-main">
  <nav className="detail-breadcrumb"><a href="/"><Icon name="home"/>Home</a><span>›</span><a href="/products">Products</a><span>›</span><b>{product.name}</b></nav>
  <section className="detail-top"><div className="detail-gallery"><div className="detail-thumbs">{views.map((mode,index)=><button className={view===index?'active':''} key={mode} onClick={()=>setView(index)} aria-label={`Show ${mode} view`}><span className={mode}><img src={product.image} alt=""/></span></button>)}</div><div className={`detail-stage ${views[view]}`}><img className="detail-stage-bg" src="/contact-hero-premium-v2.png" alt=""/><img className="detail-pack" src={product.image} alt={`${product.name} 250 gram pack`}/>{view!==2&&<img className="detail-bowl" src="/contact-community-makhana-v2.png" alt="Bowl of roasted makhana"/>}<button className={`detail-heart ${liked?'liked':''}`} onClick={onToggleLike} aria-label={liked?'Remove from wishlist':'Add to wishlist'}><Icon name="heart"/></button><button className="detail-share" onClick={share} aria-label="Share product"><Icon name="share"/></button><button className="gallery-prev" onClick={()=>setView((view+views.length-1)%views.length)} aria-label="Previous image">‹</button><button className="gallery-next" onClick={()=>setView((view+1)%views.length)} aria-label="Next image">›</button><span className="zoom-hint">⌕ &nbsp; Tap image views to zoom</span></div></div>
   <div className="detail-summary"><p className="verified">Meena Green <Icon name="check"/></p><h1>{product.name} Makhana<br/><span>(100% Natural, Roasted) – 250 g</span></h1><div className="rating-line"><strong>★★★★★</strong><b>★ 4.5</b><span>12,845 Ratings &amp; 1,206 Reviews</span></div><div className="detail-price"><strong>₹{product.price}</strong><del>₹{original}</del><span>{discount}% OFF</span></div><p className="per-pack">₹{product.price} / Pack (₹{(product.price/250).toFixed(2)}/g)</p>
    <button className="coupon" onClick={async()=>{try{await navigator.clipboard.writeText('SAVE10')}catch{}setNotice('Coupon SAVE10 copied')}}><Icon name="tag"/><span>Apply coupon <b>SAVE10</b></span><i/>Get 10% OFF up to ₹100 <b>›</b></button>
    <h2>Available Offers</h2><div className="offers">{[['gift','Bank Offer','Get 5% Cashback on SBI Credit Card'],['gift','Buy More Save More','Buy 2 Get 5% Off'],['truck','Free Delivery','on orders above ₹499']].map(([icon,title,text])=><div key={title}><span><Icon name={icon}/></span><b>{title}</b><p>{text}</p><button onClick={()=>setNotice(`${title} terms opened`)}>T&amp;C</button></div>)}</div>
    <div className="quantity-row"><b>Quantity</b><div><button onClick={()=>setQuantity(Math.max(1,quantity-1))} aria-label="Decrease quantity">−</button><strong>{quantity}</strong><button onClick={()=>setQuantity(quantity+1)} aria-label="Increase quantity">+</button></div><span>● &nbsp;In Stock</span></div>
    <div className="detail-actions"><button onClick={add}><Icon name="cart"/>Add to Cart</button><button onClick={buy}><Icon name="bolt"/>Buy Now</button></div><div className="micro-trust"><span><Icon name="shield"/>Secure Packaging</span><span><Icon name="return"/>Easy Returns</span><span><Icon name="check"/>Genuine Product</span><span><Icon name="truck"/>Pan India Delivery</span></div>
   </div></section>
  <section className="feature-strip">{features.map(([icon,title,text])=><article key={title}><span><Icon name={icon}/></span><b>{title}</b><small>{text}</small></article>)}</section>
  <section className="detail-info-grid"><article><h2><Icon name="truck"/>Delivery Details <button onClick={()=>setEditPin(!editPin)}>Change</button></h2>{editPin?<form onSubmit={e=>{e.preventDefault();setEditPin(false);setNotice(`Delivery location updated to ${pin}`)}}><input value={pin} maxLength="6" onChange={e=>setPin(e.target.value.replace(/\D/g,''))} aria-label="PIN code"/><button>Save</button></form>:<p><Icon name="pin"/><b>Purnea, Bihar - {pin}</b></p>}<p><Icon name="calendar"/><span><b>Delivery by 3 - 5 Days</b><small>Standard Delivery</small></span><strong>Free</strong></p><p><Icon name="card"/>Cash on Delivery | UPI | Cards | Net Banking</p></article><article><h2><Icon name="file"/>Product Details</h2><dl><div><dt>Brand</dt><dd>Meena Green</dd></div><div><dt>Net Weight</dt><dd>250 g</dd></div><div><dt>Flavour</dt><dd>{product.type.replace(' Makhana','')}</dd></div><div><dt>Diet Type</dt><dd>Vegetarian</dd></div><div><dt>Package Type</dt><dd>Pouch</dd></div><div><dt>Country of Origin</dt><dd>India</dd></div></dl></article><article><h2><Icon name="shield"/>Why Choose Meena Green?</h2>{[['leaf','Farm Fresh Sourcing','Direct from trusted farmers'],['shield','Hygienically Processed','Ensuring purity and safety'],['protein','Rich Nutrition','Goodness in every bite'],['star','Trusted by 1M+ Customers','Loved across India']].map(([icon,title,text])=><div className="why-detail" key={title}><span><Icon name={icon}/></span><p><b>{title}</b><small>{text}</small></p></div>)}</article></section>
  <section className="reviews-section"><header><h2><Icon name="star"/>Ratings &amp; Reviews</h2><button onClick={()=>setNotice('Showing all customer reviews')}>View All Reviews →</button></header><div className="reviews-grid"><aside><strong>4.5<small>/5</small></strong><b>★★★★★</b><p>12,845 Ratings &amp; 1,206 Reviews</p>{[72,16,7,3,2].map((n,i)=><div className="rating-bar" key={n}><span>{5-i} ★</span><i><b style={{width:`${n}%`}}/></i><small>{n}%</small></div>)}<button onClick={()=>setReviewOpen(!reviewOpen)}>Write a Review</button>{reviewOpen&&<form onSubmit={e=>{e.preventDefault();setReviewOpen(false);setNotice('Thank you! Your review was submitted.')}}><textarea required placeholder="Share your experience"/><button>Submit Review</button></form>}</aside><div className="review-cards">{reviews.map(([initial,name,text],index)=><article key={name}><header><span>{initial}</span><p><b>{name}</b><small>✓ Verified Purchase</small></p></header><strong>★★★★★</strong><p>{text}</p><button onClick={e=>{e.currentTarget.dataset.helpful='true';setNotice(`Marked ${name}’s review helpful`)}}><Icon name="thumb"/>Helpful ({48-index*13})</button></article>)}</div></div></section>
 </main>{notice&&<div className="detail-toast" role="status">{notice}<button onClick={()=>setNotice('')}>×</button></div>}<div className="detail-sticky"><img src={product.image} alt=""/><p><b>{product.name} Makhana</b><small>250 g</small></p><strong>₹{product.price*quantity}</strong><div><button onClick={()=>setQuantity(Math.max(1,quantity-1))}>−</button><b>{quantity}</b><button onClick={()=>setQuantity(quantity+1)}>+</button></div><button onClick={add}><Icon name="cart"/>Add to Cart</button><button onClick={buy}><Icon name="bolt"/>Buy Now</button></div><Footer/></div>
}
