import {useState} from 'react'
import StoreNavbar from './StoreNavbar'
import './SavedAddressesPage.css'

const icons={bag:<><path d="M5 8h14l-1 13H6L5 8Z"/><path d="M9 9V6a3 3 0 0 1 6 0v3"/></>,pin:<><path d="M19 10c0 5-7 12-7 12S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/></>,heart:<path d="M20.8 5.6a5.2 5.2 0 0 0-7.4 0L12 7l-1.4-1.4a5.2 5.2 0 0 0-7.4 7.4L12 21l8.8-8a5.2 5.2 0 0 0 0-7.4Z"/>,user:<><circle cx="12" cy="7" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>,headset:<><path d="M4 14v-2a8 8 0 0 1 16 0v2M4 14h3v6H5a1 1 0 0 1-1-1v-5Zm16 0h-3v6h2a1 1 0 0 0 1-1v-5Z"/></>,logout:<><path d="M10 17l5-5-5-5M15 12H3M14 4h5a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2h-5"/></>,home:<><path d="m3 11 9-8 9 8v10h-6v-7H9v7H3Z"/><path d="M7 11.5 12 7l5 4.5"/></>,office:<><path d="M5 21V4h10v17M9 8h2m-2 4h2m-2 4h2M15 10h4v11M3 21h18"/></>,edit:<><path d="m4 20 4.5-1 10-10a2.1 2.1 0 0 0-3-3l-10 10L4 20ZM14 7l3 3"/></>,trash:<><path d="M4 7h16M9 7V4h6v3m3 0-1 14H7L6 7m4 4v6m4-6v6"/></>,check:<path d="m5 12 4 4L19 6"/>,plus:<path d="M12 5v14M5 12h14"/>,more:<><circle cx="12" cy="5" r="1" fill="currentColor"/><circle cx="12" cy="12" r="1" fill="currentColor"/><circle cx="12" cy="19" r="1" fill="currentColor"/></>,mail:<><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m4 7 8 6 8-6"/></>,phone:<path d="M6.5 3h3l1.5 5-2 1.5a16 16 0 0 0 5.5 5.5l1.5-2 5 1.5v3c0 2-1.6 3.6-3.6 3.5C9.8 20.4 3.6 14.2 3.1 6.6 3 4.6 4.5 3 6.5 3Z"/>}
const extraIcons={card:<><rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 10h18"/></>,bell:<><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></>,settings:<><circle cx="12" cy="12" r="3"/><path d="M12 2v3m0 14v3M4.9 4.9 7 7m10 10 2.1 2.1M2 12h3m14 0h3M4.9 19.1 7 17m10-10 2.1-2.1"/></>,truck:<><path d="M3 6h11v11H3zM14 10h4l3 4v3h-7z"/><circle cx="7" cy="19" r="2"/><circle cx="18" cy="19" r="2"/></>,leaf:<><path d="M20 4C11 4 5 9 5 18c9 0 15-6 15-14Z"/><path d="M5 18 20 4"/></>}
function Icon({name,className='h-5 w-5'}){return <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" aria-hidden="true">{icons[name]||extraIcons[name]}</svg>}
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
const samples=[{id:1,label:'Home',line1:'85 P, Barauni – Purnea Hwy',line2:'Maranga, Purnia, Bihar 854301',phone:'+91 91234 56789',default:true,type:'home'},{id:2,label:'Office',line1:'2nd Floor, Sagar Building',line2:'Naya Tola, Purnia, Bihar 854301',phone:'+91 98765 43210',default:false,type:'office'},{id:3,label:"Parents’ Home",line1:'Ward No. 12, Near Market',line2:'Kursela, Katihar, Bihar 854326',phone:'+91 91234 56789',default:false,type:'family'},{id:4,label:'Other',line1:'Hostel, RK University',line2:'Rajkot, Gujarat 360020',phone:'+91 91234 56789',default:false,type:'other'}]
const menu=[['user','My Profile','/profile'],['bag','My Orders','/orders'],['pin','Saved Addresses','/addresses'],['heart','Wishlist','/profile/wishlist'],['card','Payment Methods','/profile#payment-methods'],['bell','Notifications','#'],['headset','Help & Support','/contact'],['settings','Settings','/profile']]
export default function SavedAddressesPage(){
 const wishlist=read('meena-wishlist',[])
 const [addresses,setAddresses]=useState(()=>read('meena-addresses',samples)),[editing,setEditing]=useState(null),[activeMenu,setActiveMenu]=useState('Saved Addresses')
 const persist=next=>{setAddresses(next);localStorage.setItem('meena-addresses',JSON.stringify(next))}
 const startNew=()=>setEditing({id:Date.now(),label:'',line1:'',line2:'',phone:'',default:addresses.length===0,type:'home'})
 const submit=e=>{e.preventDefault();const exists=addresses.some(x=>x.id===editing.id);let next=exists?addresses.map(x=>x.id===editing.id?editing:x):[editing,...addresses];if(editing.default)next=next.map(x=>({...x,default:x.id===editing.id}));persist(next);setEditing(null)}
 const logout=()=>{localStorage.removeItem('meena-auth');history.pushState({},'','/login');window.dispatchEvent(new PopStateEvent('popstate'))}
 const selectMenu=(event,label,href)=>{setActiveMenu(label);if(href==='#')event.preventDefault()}
 return <><StoreNavbar wishlistCount={wishlist.length}/><main className="min-h-screen bg-[#fffdf8] px-4 py-7 text-[#103d30] lg:px-8"><div className="mx-auto grid max-w-[1480px] items-start gap-5 lg:grid-cols-[305px_1fr]">
  <aside className="rounded-2xl border border-[#dce6df] bg-white p-4 shadow-[0_8px_26px_rgba(7,59,39,.05)] lg:sticky lg:top-[150px]"><header className="px-3 pb-4"><h1 className="font-serif text-2xl font-bold text-[#092d2a]">My Account</h1><p className="mt-1 text-sm text-slate-500">Manage your profile, orders and more</p></header><nav className="flex flex-col gap-1">{menu.map(([icon,label,href])=>{const active=activeMenu===label;return <a key={label} href={href} onClick={event=>selectMenu(event,label,href)} className={`flex h-[58px] items-center gap-5 rounded-xl px-4 !text-[16px] !font-medium !leading-none transition-all duration-300 ${active?'bg-[#087848] !text-white shadow-[0_8px_18px_rgba(0,105,63,.2)] hover:bg-[#00663d]':'!text-[#0b2545] hover:translate-x-1 hover:bg-[#eff8ee]'}`}><Icon name={icon} className={`h-6 w-6 shrink-0 transition-transform duration-300 ${active?'text-white':'text-[#07804b]'}`}/><span className="flex-1">{label}</span>{active&&<span className="text-2xl">›</span>}</a>})}</nav><div className="mx-3 my-3 border-t"/><button onClick={logout} className="flex h-[58px] we w-full items-center gap-5 !border-0 !bg-transparent px-4 !text-[16px] !font-medium !text-red-600 transition-all duration-300 hover:translate-x-1 hover:!bg-red-50"><Icon name="logout" className="h-6 w-6"/>Logout</button><div className="relative mt-5 hidden min-h-[180px] overflow-hidden rounded-xl bg-[#f0f7e8] p-5 lg:block"><h2 className="relative z-10 font-serif text-2xl font-bold italic">Good Food<br/>Brighter Lives</h2><p className="relative z-10 mt-5 max-w-[150px] text-sm">Pure makhana for a healthier you!</p><img src="/wishlist-hero-banner.png" alt="" className="absolute bottom-0 right-0 h-28 w-full object-cover object-right"/></div></aside>
  <section className="addresses-content"><header className="addresses-heading"><div className="addresses-title"><span><Icon name="pin"/></span><div><h1>Saved Addresses</h1><p>Manage your delivery addresses for a faster checkout experience.</p></div></div><button onClick={startNew} className="address-primary"><Icon name="plus"/>Add New Address</button></header>
   <div className="address-tip"><Icon name="truck"/><span>Save your addresses to get faster delivery and a smoother shopping experience.</span></div>
   {editing&&<form onSubmit={submit} className="address-form"><header><div><h2>{addresses.some(x=>x.id===editing.id)?'Edit Address':'Add New Address'}</h2><p>Add complete details so your order reaches the right place.</p></div><button type="button" onClick={()=>setEditing(null)} aria-label="Close address form">×</button></header><div className="address-form-grid"><label>Address Label<input required placeholder="Home, Office..." value={editing.label} onChange={e=>{const label=e.target.value;const lower=label.toLowerCase();setEditing({...editing,label,type:lower.includes('office')?'office':lower.includes('parent')||lower.includes('family')?'family':lower.includes('other')?'other':'home'})}}/></label><label>Phone Number<input required type="tel" value={editing.phone} onChange={e=>setEditing({...editing,phone:e.target.value})}/></label><label>Street / Building<input required value={editing.line1} onChange={e=>setEditing({...editing,line1:e.target.value})}/></label><label>City, State and PIN Code<input required value={editing.line2} onChange={e=>setEditing({...editing,line2:e.target.value})}/></label></div><label className="address-default-check"><input type="checkbox" checked={editing.default} onChange={e=>setEditing({...editing,default:e.target.checked})}/>Use as default delivery address</label><div className="address-form-actions"><button type="button" className="address-outline" onClick={()=>setEditing(null)}>Cancel</button><button className="address-primary"><Icon name="check"/>Save Address</button></div></form>}
   <div className="address-list">{addresses.map(address=>{const kind=address.type==='office'?'office':address.type==='family'?'family':address.type==='other'?'other':'home';const icon=kind==='office'?'office':kind==='family'?'heart':kind==='other'?'pin':'home';return <article key={address.id} className={`address-card ${kind}`}><div className="address-main"><span className="address-icon"><Icon name={icon}/></span><div className="address-copy"><div className="address-name"><h2>{address.label}</h2>{address.default&&<span>Default</span>}</div><p>{address.line1}<br/>{address.line2}</p><a href={`tel:${address.phone.replace(/\s/g,'')}`}><Icon name="phone"/>{address.phone}</a></div><button className="address-more" aria-label={`${address.label} address options`}><Icon name="more"/></button></div><footer><div className="address-tags"><span><Icon name={kind==='family'?'heart':kind==='office'?'bag':'pin'}/>{address.label}</span><span><Icon name="phone"/>{address.default?'Primary':'Secondary'}</span><button onClick={()=>persist(addresses.map(x=>({...x,default:x.id===address.id})))} aria-pressed={address.default}><Icon name="truck"/>{address.default?'Delivery address':'Deliver to this address'}</button></div><div className="address-actions"><button className="address-edit" onClick={()=>setEditing({...address})}><Icon name="edit"/>Edit</button><button className="address-delete" onClick={()=>persist(addresses.filter(x=>x.id!==address.id))}><Icon name="trash"/>Delete</button></div></footer></article>})}</div>
   {!addresses.length&&<div className="address-empty"><span><Icon name="pin"/></span><h2>No saved address yet</h2><p>Add your first delivery address for a faster checkout.</p><button onClick={startNew} className="address-primary"><Icon name="plus"/>Add Address</button></div>}
  </section></div></main></>
}
