import {useState} from 'react'
import StoreNavbar from './StoreNavbar'

const icons={bag:<><path d="M5 8h14l-1 13H6L5 8Z"/><path d="M9 9V6a3 3 0 0 1 6 0v3"/></>,pin:<><path d="M19 10c0 5-7 12-7 12S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/></>,heart:<path d="M20.8 5.6a5.2 5.2 0 0 0-7.4 0L12 7l-1.4-1.4a5.2 5.2 0 0 0-7.4 7.4L12 21l8.8-8a5.2 5.2 0 0 0 0-7.4Z"/>,user:<><circle cx="12" cy="7" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>,headset:<><path d="M4 14v-2a8 8 0 0 1 16 0v2M4 14h3v6H5a1 1 0 0 1-1-1v-5Zm16 0h-3v6h2a1 1 0 0 0 1-1v-5Z"/></>,logout:<><path d="M10 17l5-5-5-5M15 12H3M14 4h5a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2h-5"/></>,home:<><path d="m3 11 9-8 9 8v10h-6v-7H9v7H3Z"/><path d="M7 11.5 12 7l5 4.5"/></>,office:<><path d="M5 21V4h10v17M9 8h2m-2 4h2m-2 4h2M15 10h4v11M3 21h18"/></>,edit:<><path d="m4 20 4.5-1 10-10a2.1 2.1 0 0 0-3-3l-10 10L4 20ZM14 7l3 3"/></>,trash:<><path d="M4 7h16M9 7V4h6v3m3 0-1 14H7L6 7m4 4v6m4-6v6"/></>,check:<path d="m5 12 4 4L19 6"/>,plus:<path d="M12 5v14M5 12h14"/>,more:<><circle cx="12" cy="5" r="1" fill="currentColor"/><circle cx="12" cy="12" r="1" fill="currentColor"/><circle cx="12" cy="19" r="1" fill="currentColor"/></>,mail:<><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m4 7 8 6 8-6"/></>,phone:<path d="M6.5 3h3l1.5 5-2 1.5a16 16 0 0 0 5.5 5.5l1.5-2 5 1.5v3c0 2-1.6 3.6-3.6 3.5C9.8 20.4 3.6 14.2 3.1 6.6 3 4.6 4.5 3 6.5 3Z"/>}
const extraIcons={card:<><rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 10h18"/></>,bell:<><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></>,settings:<><circle cx="12" cy="12" r="3"/><path d="M12 2v3m0 14v3M4.9 4.9 7 7m10 10 2.1 2.1M2 12h3m14 0h3M4.9 19.1 7 17m10-10 2.1-2.1"/></>}
function Icon({name,className='h-5 w-5'}){return <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" aria-hidden="true">{icons[name]||extraIcons[name]}</svg>}
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
const samples=[{id:1,label:'Home',line1:'85 P, Barauni – Purnea Hwy',line2:'Maranga, Purnia, Bihar 854301',phone:'+91 91234 56789',default:true,type:'home'},{id:2,label:'Office',line1:'2nd Floor, Sagar Building',line2:'Naya Tola, Purnia, Bihar 854301',phone:'+91 98765 43210',default:false,type:'office'}]
const menu=[['user','My Profile','/profile'],['bag','My Orders','/orders'],['pin','Saved Addresses','/addresses'],['heart','Wishlist','/profile/wishlist'],['card','Payment Methods','/profile#payment-methods'],['bell','Notifications','#'],['headset','Help & Support','/contact'],['settings','Settings','/profile']]
const primary='inline-flex h-11 items-center justify-center gap-2 rounded-lg !border-0 !bg-[#067345] px-6 !text-[13px] !font-semibold !leading-none !text-white shadow-[0_8px_18px_rgba(0,105,63,.18)] hover:!bg-[#005f39]'
const outline='inline-flex h-12 items-center justify-center gap-2 rounded-lg !border !border-[#bfd3c6] !bg-white px-6 !text-[15px] !font-semibold !leading-none !text-[#08623f] hover:!bg-[#f4faf4]'

export default function SavedAddressesPage(){
 const profile=read('meena-profile',{name:'Meena Customer',email:'customer@meenagreen.in',phone:'+91 98765 43210'}),wishlist=read('meena-wishlist',[])
 const [addresses,setAddresses]=useState(()=>read('meena-addresses',samples)),[editing,setEditing]=useState(null),[activeMenu,setActiveMenu]=useState('Saved Addresses')
 const initials=(profile.name||'Meena Customer').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()
 const persist=next=>{setAddresses(next);localStorage.setItem('meena-addresses',JSON.stringify(next))}
 const startNew=()=>setEditing({id:Date.now(),label:'',line1:'',line2:'',phone:'',default:addresses.length===0,type:'home'})
 const submit=e=>{e.preventDefault();const exists=addresses.some(x=>x.id===editing.id);let next=exists?addresses.map(x=>x.id===editing.id?editing:x):[editing,...addresses];if(editing.default)next=next.map(x=>({...x,default:x.id===editing.id}));persist(next);setEditing(null)}
 const logout=()=>{localStorage.removeItem('meena-auth');history.pushState({},'','/login');window.dispatchEvent(new PopStateEvent('popstate'))}
 const selectMenu=(event,label,href)=>{setActiveMenu(label);if(href==='#')event.preventDefault()}
 return <><StoreNavbar wishlistCount={wishlist.length}/><main className="min-h-screen bg-[#fffdf8] px-4 py-7 text-[#103d30] lg:px-8"><div className="mx-auto grid max-w-[1480px] items-start gap-5 lg:grid-cols-[305px_1fr]">
  <aside className="rounded-2xl border border-[#dce6df] bg-white p-4 shadow-[0_8px_26px_rgba(7,59,39,.05)] lg:sticky lg:top-[150px]"><header className="px-3 pb-4"><h1 className="font-serif text-2xl font-bold text-[#092d2a]">My Account</h1><p className="mt-1 text-sm text-slate-500">Manage your profile, orders and more</p></header><nav className="flex flex-col gap-1">{menu.map(([icon,label,href])=>{const active=activeMenu===label;return <a key={label} href={href} onClick={event=>selectMenu(event,label,href)} className={`flex h-[58px] items-center gap-5 rounded-xl px-4 !text-[16px] !font-medium !leading-none transition-all duration-300 ${active?'bg-[#087848] !text-white shadow-[0_8px_18px_rgba(0,105,63,.2)] hover:bg-[#00663d]':'!text-[#0b2545] hover:translate-x-1 hover:bg-[#eff8ee]'}`}><Icon name={icon} className={`h-6 w-6 shrink-0 transition-transform duration-300 ${active?'text-white':'text-[#07804b]'}`}/><span className="flex-1">{label}</span>{active&&<span className="text-2xl">›</span>}</a>})}</nav><div className="mx-3 my-3 border-t"/><button onClick={logout} className="flex h-[58px] we w-full items-center gap-5 !border-0 !bg-transparent px-4 !text-[16px] !font-medium !text-red-600 transition-all duration-300 hover:translate-x-1 hover:!bg-red-50"><Icon name="logout" className="h-6 w-6"/>Logout</button><div className="relative mt-5 hidden min-h-[180px] overflow-hidden rounded-xl bg-[#f0f7e8] p-5 lg:block"><h2 className="relative z-10 font-serif text-2xl font-bold italic">Good Food<br/>Brighter Lives</h2><p className="relative z-10 mt-5 max-w-[150px] text-sm">Pure makhana for a healthier you!</p><img src="/wishlist-hero-banner.png" alt="" className="absolute bottom-0 right-0 h-28 w-full object-cover object-right"/></div></aside>
  <section className="space-y-5"><div className="relative min-h-[178px] overflow-hidden rounded-2xl border border-[#dce6df] bg-[#f5f9ef] p-6 shadow-sm"><img src="/wishlist-hero-banner.png" alt="" className="absolute inset-0 h-full w-full object-cover object-right"/><div className="absolute inset-0 bg-gradient-to-r from-[#f7fbf1] via-[#f7fbf1]/95 to-transparent"/><div className="relative flex items-center gap-6"><span className="grid h-28 w-28 shrink-0 place-items-center rounded-full border-4 border-white bg-[#087047] text-4xl font-bold text-white shadow-lg">{initials}</span><div className="min-w-0 flex-1"><h2 className="font-serif text-3xl font-bold text-[#075e3a]">{profile.name}</h2><div className="mt-3 flex flex-wrap gap-x-6 gap-y-2 text-slate-500"><span className="flex items-center gap-2"><Icon name="mail"/>{profile.email||'Email not added'}</span><span className="flex items-center gap-2"><Icon name="phone"/>{profile.phone||'Phone not added'}</span></div><span className="mt-4 inline-flex rounded-full bg-[#e7f5dc] px-4 py-2 text-sm font-semibold">♛ &nbsp; Regular Customer</span></div><a href="/profile" className={`${outline} self-start`}><Icon name="edit"/>Edit Profile</a></div></div>
   <div className="rounded-2xl border border-[#dce6df] bg-white p-4 shadow-[0_8px_26px_rgba(7,59,39,.05)] sm:p-5"><header className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><h1 className="font-serif text-[26px] font-bold leading-tight text-[#075e3a]">Saved Addresses</h1><p className="mt-1 text-[13px] text-slate-500">Manage your saved delivery addresses.</p></div><button onClick={startNew} className={primary}><Icon name="plus" className="h-4 w-4"/>Add New Address</button></header>
    {editing&&<form onSubmit={submit} className="rounded-xl border border-[#d6dfd8] bg-[#fffefb] p-5"><h2 className="mb-5 text-lg font-semibold text-[#087046]">{addresses.some(x=>x.id===editing.id)?'Edit Address':'Add New Address'}</h2><div className="grid gap-3 sm:grid-cols-2"><label className="text-[11px] font-semibold">Address Label<input required placeholder="Home, Office..." value={editing.label} onChange={e=>setEditing({...editing,label:e.target.value,type:e.target.value.toLowerCase().includes('office')?'office':'home'})} className="mt-1.5 h-10 w-full rounded-md border border-[#bcd2c6] bg-white px-3 text-xs font-normal outline-none focus:border-[#087046]"/></label><label className="text-[11px] font-semibold">Phone Number<input required value={editing.phone} onChange={e=>setEditing({...editing,phone:e.target.value})} className="mt-1.5 h-10 w-full rounded-md border border-[#bcd2c6] bg-white px-3 text-xs font-normal outline-none focus:border-[#087046]"/></label><label className="text-[11px] font-semibold sm:col-span-2">Street / Building<input required value={editing.line1} onChange={e=>setEditing({...editing,line1:e.target.value})} className="mt-1.5 h-10 w-full rounded-md border border-[#bcd2c6] bg-white px-3 text-xs font-normal outline-none focus:border-[#087046]"/></label><label className="text-[11px] font-semibold sm:col-span-2">City, State and PIN Code<input required value={editing.line2} onChange={e=>setEditing({...editing,line2:e.target.value})} className="mt-1.5 h-10 w-full rounded-md border border-[#bcd2c6] bg-white px-3 text-xs font-normal outline-none focus:border-[#087046]"/></label></div><label className="mt-4 flex items-center gap-2 text-[11px] font-semibold"><input type="checkbox" checked={editing.default} onChange={e=>setEditing({...editing,default:e.target.checked})} className="h-4 w-4 accent-[#087046]"/>Use as default delivery address</label><div className="mt-5 flex justify-end gap-3"><button type="button" onClick={()=>setEditing(null)} className="h-10 rounded-lg !border !border-[#bfd3c6] !bg-white px-5 !text-xs !font-semibold !text-[#08623f]">Cancel</button><button className="h-10 rounded-lg !border-0 !bg-[#087046] px-5 !text-xs !font-semibold !text-white hover:!bg-[#005d39]">Save Address</button></div></form>}
    <div className="mt-0 space-y-3">{addresses.map(address=><article key={address.id} className="rounded-xl border border-[#d7dfd9] px-4 py-4"><div className="flex gap-4"><span className="grid h-14 w-14 shrink-0 place-items-center rounded-lg bg-[#edf6e9] text-[#087046]"><Icon name={address.type==='office'?'office':'home'} className="h-7 w-7"/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-3"><h2 className="text-base font-semibold">{address.label}</h2>{address.default&&<span className="rounded-md bg-[#e8f3dc] px-2 py-1 text-[10px] font-bold text-[#4b8540]">Default</span>}</div><p className="mt-1 text-[11px] leading-relaxed text-slate-500">{address.line1}<br/>{address.line2}<br/>{address.phone}</p></div><button className="h-8 w-8 !border-0 !bg-transparent text-[#17483b]" aria-label={`${address.label} address options`}><Icon name="more" className="h-5 w-5"/></button></div><div className="mt-3 flex flex-wrap items-center gap-6 border-t border-dashed border-[#e1e6e2] pt-3"><button onClick={()=>setEditing({...address})} className="inline-flex items-center gap-2 !border-0 !bg-transparent !text-xs !font-medium !text-[#087046]"><Icon name="edit" className="h-4 w-4"/>Edit</button><button onClick={()=>persist(addresses.filter(x=>x.id!==address.id))} className="inline-flex items-center gap-2 !border-0 !bg-transparent !text-xs !font-medium !text-red-600"><Icon name="trash" className="h-4 w-4"/>Delete</button><button onClick={()=>persist(addresses.map(x=>({...x,default:x.id===address.id})))} className="ml-auto inline-flex h-9 items-center gap-2 rounded-lg !border !border-[#c8ddcd] !bg-[#f4faf2] px-4 !text-[11px] !font-semibold !text-[#087046]"><Icon name="check" className="h-4 w-4"/>{address.default?'Default Address':'Set as Default'}</button></div></article>)}</div>
    {!addresses.length&&<div className="rounded-xl border border-dashed border-[#9ac7ad] p-10 text-center text-slate-500">No saved address yet. Add your first delivery address.</div>}<div className="mt-4 rounded-xl bg-[#eef5e9] px-5 py-4 text-sm text-[#267150]">✓ &nbsp; Your default address will be used for all deliveries.</div>
   </div>
  </section></div></main></>
}
