import {useState} from 'react'
import StoreNavbar from './StoreNavbar'
import AccountSidebar from './AccountSidebar'
import './SettingsPage.css'

const paths={user:<><circle cx="12" cy="7" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>,pin:<><path d="M19 10c0 5-7 12-7 12S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/></>,id:<><rect x="3" y="5" width="18" height="14" rx="2"/><circle cx="8" cy="11" r="2"/><path d="M5 16c.8-2 5.2-2 6 0m3-6h4m-4 4h4"/></>,link:<><path d="m10 13 4-4m-6 8-2 2a3 3 0 0 1-4-4l4-4a3 3 0 0 1 4 0m6-4 2-2a3 3 0 0 1 4 4l-4 4a3 3 0 0 1-4 0"/></>,bell:<><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></>,globe:<><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c3 3 3 15 0 18M12 3c-3 3-3 15 0 18"/></>,rupee:<path d="M6 5h12M6 9h12M7 5c7 0 7 8 0 8h-1l9 7"/>,moon:<><path d="M20 15a8 8 0 0 1-11-11 9 9 0 1 0 11 11Z"/></>,lock:<><rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3M12 15v2"/></>,shield:<><path d="M12 3 20 6v6c0 5-3.4 8-8 10-4.6-2-8-5-8-10V6l8-3Z"/><path d="m8.5 12 2.3 2.3 4.8-5"/></>,eye:<><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="2.5"/></>,settings:<><circle cx="12" cy="12" r="3"/><path d="M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M19 5l-2 2M7 17l-2 2"/></>,info:<><circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10h.01"/></>,document:<><path d="M6 2h8l4 4v16H6Z"/><path d="M14 2v5h5M9 12h6m-6 4h6"/></>,refresh:<><path d="M20 7v5h-5M4 17v-5h5"/><path d="M6.1 9a7 7 0 0 1 12-2l2 5M17.9 15a7 7 0 0 1-12 2l-2-5"/></>,trash:<><path d="M4 7h16M9 7V4h6v3m3 0-1 14H7L6 7m4 4v6m4-6v6"/></>,chevron:<path d="m9 5 7 7-7 7"/>,close:<path d="m6 6 12 12M18 6 6 18"/>,check:<path d="m6 12 4 4 8-9"/>}
function Icon({name}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>}
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
const go=path=>{history.pushState({},'',path);window.dispatchEvent(new PopStateEvent('popstate'));window.scrollTo({top:0,behavior:'smooth'})}
const groups=[
 ['Account Settings',[['profile','user','Edit Profile','Update your name, email, mobile number and profile photo'],['addresses','pin','Manage Addresses','Add, edit or remove saved addresses'],['pan','id','PAN Card','Add or update your PAN card details'],['accounts','link','Manage Accounts','Manage linked accounts (Google, etc.)']]],
 ['App Preferences',[['notifications','bell','Notification Settings','Choose what alerts and updates you want to receive'],['language','globe','Language','Select your preferred language'],['currency','rupee','Currency','View prices in your preferred currency'],['theme','moon','Theme','Choose light or dark mode']]],
 ['Privacy & Security',[['password','lock','Change Password','Update your account password'],['twofactor','shield','Two-Factor Authentication','Add an extra layer of security'],['privacy','eye','Privacy Settings','Manage your data and privacy preferences'],['permissions','settings','Manage App Permissions','Control app access and permissions']]],
 ['About & Legal',[['about','info','About Us','Learn more about Meena Green'],['terms','document','Terms of Use','Read our terms and conditions'],['policy','shield','Privacy Policy','Understand how we protect your data'],['returns','refresh','Return, Refund & Cancellation Policy','View our return and refund policy']]]
]

export default function SettingsPage(){
 const wishlist=read('meena-wishlist',[]),notifications=read('meena-notifications',[]),notificationCount=Array.isArray(notifications)?notifications.filter(item=>item.unread).length:0
 const [panel,setPanel]=useState(null),[notice,setNotice]=useState(''),[prefs,setPrefs]=useState(()=>read('meena-settings',{language:'English',currency:'INR (₹)',theme:'Light',emailAlerts:true,pushAlerts:true,orderUpdates:true,analytics:false,personalization:true,twoFactor:false,google:true})),[pan,setPan]=useState(()=>read('meena-pan','')),[deleteText,setDeleteText]=useState('')
 const toast=message=>{setNotice(message);window.setTimeout(()=>setNotice(''),2500)}
 const savePrefs=next=>{setPrefs(next);localStorage.setItem('meena-settings',JSON.stringify(next))}
 const choose=(key,value)=>savePrefs({...prefs,[key]:value})
 const open=id=>{if(id==='profile')return go('/profile');if(id==='addresses')return go('/addresses');if(id==='about')return go('/about');setPanel(id)}
 const close=()=>{setPanel(null);setDeleteText('')}
 const savePanel=message=>{localStorage.setItem('meena-settings',JSON.stringify(prefs));close();toast(message)}
 const deleteAccount=()=>{['meena-auth','meena-profile','meena-addresses','meena-order-history','meena-settings'].forEach(key=>localStorage.removeItem(key));go('/login')}
 return <><StoreNavbar active="account" wishlistCount={wishlist.length||1}/><main className={`settings-page theme-${prefs.theme.toLowerCase()}`}><div className="settings-shell"><AccountSidebar active="Settings" wishlistCount={wishlist.length||1} notificationCount={notificationCount}/><section className="settings-main">
  <header className="settings-heading"><h1>Settings</h1><p>Manage your account preferences and app settings</p></header>
  {groups.map(([title,items])=><section className="settings-group" key={title}><h2>{title}</h2><div>{items.map(([id,icon,label,description])=><button key={id} onClick={()=>open(id)}><i><Icon name={icon}/></i><span><b>{label}</b><small>{description}</small></span>{id==='language'&&<em>{prefs.language}</em>}{id==='currency'&&<em>{prefs.currency}</em>}{id==='theme'&&<em>{prefs.theme}</em>}<Icon name="chevron"/></button>)}</div></section>)}
  <button className="settings-delete-row" onClick={()=>setPanel('delete')}><i><Icon name="trash"/></i><span><b>Delete Account</b><small>Permanently delete your account and data</small></span><Icon name="chevron"/></button>
 </section></div></main>
 {panel&&<SettingsModal panel={panel} close={close} prefs={prefs} choose={choose} pan={pan} setPan={setPan} savePanel={savePanel} deleteText={deleteText} setDeleteText={setDeleteText} deleteAccount={deleteAccount}/>} {notice&&<div className="settings-toast" role="status"><Icon name="check"/>{notice}</div>}</>
}

function SettingsModal({panel,close,prefs,choose,pan,setPan,savePanel,deleteText,setDeleteText,deleteAccount}){
 const titles={pan:'PAN Card',accounts:'Manage Accounts',language:'Language',currency:'Currency',theme:'Theme',password:'Change Password',twofactor:'Two-Factor Authentication',privacy:'Privacy Settings',permissions:'App Permissions',terms:'Terms of Use',policy:'Privacy Policy',returns:'Return, Refund & Cancellation Policy',delete:'Delete Account'}
 const toggle=(key,label)=><label className="settings-toggle-row"><span><b>{label}</b><small>{prefs[key]?'Enabled':'Disabled'}</small></span><input type="checkbox" checked={Boolean(prefs[key])} onChange={event=>choose(key,event.target.checked)}/><i/></label>
 const options=(key,values)=> <div className="settings-options">{values.map(value=><label key={value} className={prefs[key]===value?'selected':''}><input type="radio" name={key} checked={prefs[key]===value} onChange={()=>choose(key,value)}/><span>{value}</span><Icon name="check"/></label>)}</div>
 return <div className="settings-modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><section className={`settings-modal ${panel==='delete'?'danger-modal':''}`} role="dialog" aria-modal="true" aria-labelledby="settings-modal-title"><header><div><i><Icon name={panel==='delete'?'trash':panel==='password'?'lock':panel==='theme'?'moon':'settings'}/></i><h2 id="settings-modal-title">{titles[panel]}</h2></div><button onClick={close} aria-label="Close settings dialog"><Icon name="close"/></button></header>
  {panel==='pan'&&<form onSubmit={event=>{event.preventDefault();localStorage.setItem('meena-pan',pan);savePanel('PAN details saved securely.')}}><label>PAN Number<input required pattern="[A-Za-z]{5}[0-9]{4}[A-Za-z]" placeholder="ABCDE1234F" value={pan} onChange={event=>setPan(event.target.value.toUpperCase())}/></label><p className="settings-note">Your PAN is stored securely on this device.</p><ModalActions close={close} label="Save PAN"/></form>}
  {panel==='accounts'&&<><div className="linked-account"><i>G</i><span><b>Google Account</b><small>{prefs.google?'Connected':'Not connected'}</small></span><button onClick={()=>choose('google',!prefs.google)}>{prefs.google?'Disconnect':'Connect'}</button></div><ModalActions close={close} label="Done" onSave={()=>savePanel('Linked accounts updated.')}/></>}
  {panel==='notifications'&&<>{toggle('orderUpdates','Order updates')}{toggle('pushAlerts','Push notifications')}{toggle('emailAlerts','Email offers and updates')}<ModalActions close={close} label="Save Preferences" onSave={()=>savePanel('Notification preferences saved.')}/></>}
  {panel==='language'&&<>{options('language',['English','हिन्दी','বাংলা'])}<ModalActions close={close} label="Apply Language" onSave={()=>savePanel('Language preference updated.')}/></>}
  {panel==='currency'&&<>{options('currency',['INR (₹)','USD ($)','EUR (€)'])}<ModalActions close={close} label="Apply Currency" onSave={()=>savePanel('Currency preference updated.')}/></>}
  {panel==='theme'&&<>{options('theme',['Light','Dark','System'])}<ModalActions close={close} label="Apply Theme" onSave={()=>savePanel('Theme preference updated.')}/></>}
  {panel==='password'&&<form onSubmit={event=>{event.preventDefault();savePanel('Password updated for this demo account.')}}><label>Current Password<input required type="password" autoComplete="current-password"/></label><label>New Password<input required type="password" minLength="8" autoComplete="new-password"/></label><label>Confirm Password<input required type="password" minLength="8" autoComplete="new-password"/></label><ModalActions close={close} label="Update Password"/></form>}
  {panel==='twofactor'&&<><div className="settings-security-note"><Icon name="shield"/><p>Add an extra verification step when signing in to your account.</p></div>{toggle('twoFactor','Two-factor authentication')}<ModalActions close={close} label="Save Security Setting" onSave={()=>savePanel('Security preference updated.')}/></>}
  {panel==='privacy'&&<>{toggle('analytics','Share anonymous usage analytics')}{toggle('personalization','Personalized recommendations')}<ModalActions close={close} label="Save Privacy Settings" onSave={()=>savePanel('Privacy settings saved.')}/></>}
  {panel==='permissions'&&<>{toggle('pushAlerts','Notification permission')}<div className="settings-static-row"><span><b>Location access</b><small>Used only to estimate delivery</small></span><em>While using app</em></div><ModalActions close={close} label="Save Permissions" onSave={()=>savePanel('App permissions updated.')}/></>}
  {['terms','policy','returns'].includes(panel)&&<><div className="settings-legal-copy"><p>{panel==='terms'?'By using Meena Green, you agree to use the store responsibly and provide accurate order and delivery information.':panel==='policy'?'We only use your information to manage your account, fulfil orders and improve your shopping experience.':'Eligible unopened products can be returned according to the displayed return window. Refunds are processed after inspection.'}</p><p>For questions, contact Meena Green Support from your account menu.</p></div><ModalActions close={close} label="I Understand" onSave={close}/></>}
  {panel==='delete'&&<><div className="settings-delete-warning"><Icon name="trash"/><p>This permanently removes your locally saved profile, addresses, orders and preferences.</p></div><label>Type DELETE to confirm<input value={deleteText} onChange={event=>setDeleteText(event.target.value)} placeholder="DELETE"/></label><div className="settings-modal-actions"><button onClick={close}>Keep Account</button><button className="danger" disabled={deleteText!=='DELETE'} onClick={deleteAccount}>Delete Account</button></div></>}
 </section></div>
}
function ModalActions({close,label,onSave}){return <div className="settings-modal-actions"><button type="button" onClick={close}>Cancel</button><button type="submit" onClick={onSave}>{label}</button></div>}
